/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package airlineticketbookingsystem.Components;

/**
 *
 * @author taake
 */
public class MainToolBar extends javax.swing.JPanel {

    /**
     * Creates new form ToolBarUser
     */
    public MainToolBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        BigSpace = new javax.swing.JPanel();
        Flights = new javax.swing.JLabel();
        space1 = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        space2 = new javax.swing.JLabel();
        SignUp = new javax.swing.JButton();
        space3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        toolbar.setBackground(new java.awt.Color(255, 255, 255));
        toolbar.setAlignmentX(0.0F);
        toolbar.setAlignmentY(0.0F);
        toolbar.setPreferredSize(new java.awt.Dimension(1440, 96));
        toolbar.setLayout(new javax.swing.BoxLayout(toolbar, javax.swing.BoxLayout.X_AXIS));

        Logo.setBackground(new java.awt.Color(153, 153, 0));
        Logo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Logo.setForeground(new java.awt.Color(96, 93, 236));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Logo.setText("Flighty");
        Logo.setToolTipText("");
        Logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Logo.setPreferredSize(new java.awt.Dimension(107, 30));
        toolbar.add(Logo);

        BigSpace.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout BigSpaceLayout = new javax.swing.GroupLayout(BigSpace);
        BigSpace.setLayout(BigSpaceLayout);
        BigSpaceLayout.setHorizontalGroup(
            BigSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1098, Short.MAX_VALUE)
        );
        BigSpaceLayout.setVerticalGroup(
            BigSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        toolbar.add(BigSpace);

        Flights.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Flights.setForeground(new java.awt.Color(96, 93, 236));
        Flights.setText("Flights");
        toolbar.add(Flights);

        space1.setPreferredSize(new java.awt.Dimension(15, 0));
        toolbar.add(space1);

        Login.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Login.setForeground(new java.awt.Color(124, 141, 176));
        Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login.setText("Login");
        toolbar.add(Login);

        space2.setPreferredSize(new java.awt.Dimension(15, 0));
        toolbar.add(space2);

        SignUp.setBackground(new java.awt.Color(96, 93, 236));
        SignUp.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        SignUp.setForeground(new java.awt.Color(255, 255, 255));
        SignUp.setText("Sign up");
        SignUp.setMaximumSize(new java.awt.Dimension(95, 48));
        SignUp.setPreferredSize(new java.awt.Dimension(95, 48));
        toolbar.add(SignUp);

        space3.setPreferredSize(new java.awt.Dimension(25, 0));
        toolbar.add(space3);

        add(toolbar);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BigSpace;
    private javax.swing.JLabel Flights;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton SignUp;
    private javax.swing.JLabel space1;
    private javax.swing.JLabel space2;
    private javax.swing.JLabel space3;
    private javax.swing.JPanel toolbar;
    // End of variables declaration//GEN-END:variables
}
