/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airlineticketbookingsystem.Pages;

import airlineticketbookingsystem.dbconnection.*;
import airlineticketbookingsystem.models.*;
import javax.swing.JOptionPane;

/**
 *
 * @author taake
 */
public class AccountAdminPage extends javax.swing.JFrame {
    UserDAO userDAO = new UserDAO();
    User user = new User();
    User cur = new User();
    String fName, lName, email, phone, password, address, zip, city, state, country, sage, gender;
    int age;
    String cfName, clName, cemail, cphone, cpassword, caddress, czip, ccity, cstate, ccountry, csage, cgender;
    int cage;
    public AccountAdminPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        cur = AppSession.getCurrentUser();
        btnclc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        toolbar = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        BigSpace = new javax.swing.JPanel();
        Flights = new javax.swing.JLabel();
        space1 = new javax.swing.JLabel();
        ManageFlights = new javax.swing.JLabel();
        space2 = new javax.swing.JLabel();
        ManageAirports = new javax.swing.JLabel();
        space3 = new javax.swing.JLabel();
        Account = new javax.swing.JButton();
        space4 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LoginPanel = new javax.swing.JPanel();
        SignUp1 = new javax.swing.JLabel();
        message_city = new javax.swing.JLabel();
        message_zip = new javax.swing.JLabel();
        message_address = new javax.swing.JLabel();
        message_confirmpassword = new javax.swing.JLabel();
        message_password = new javax.swing.JLabel();
        message_phone = new javax.swing.JLabel();
        message_email = new javax.swing.JLabel();
        message_lname = new javax.swing.JLabel();
        EnterYourName = new javax.swing.JLabel();
        message_fname = new javax.swing.JLabel();
        txt_FirstName = new javax.swing.JTextField();
        separtor1 = new javax.swing.JSeparator();
        txt_LastName = new javax.swing.JTextField();
        separtor2 = new javax.swing.JSeparator();
        EnterYourEmailAndPassword = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        separtor3 = new javax.swing.JSeparator();
        txt_Phone = new javax.swing.JTextField();
        separtor4 = new javax.swing.JSeparator();
        EnterYourPassword = new javax.swing.JLabel();
        txt_Password = new javax.swing.JTextField();
        separtor5 = new javax.swing.JSeparator();
        EnterYourAddress = new javax.swing.JLabel();
        txt_Address = new javax.swing.JTextField();
        separtor7 = new javax.swing.JSeparator();
        txt_Zip = new javax.swing.JTextField();
        separtor8 = new javax.swing.JSeparator();
        txt_City = new javax.swing.JTextField();
        separtor9 = new javax.swing.JSeparator();
        txt_State = new javax.swing.JTextField();
        separtor10 = new javax.swing.JSeparator();
        txt_Country = new javax.swing.JTextField();
        separtor11 = new javax.swing.JSeparator();
        message_country = new javax.swing.JLabel();
        EnterYourAge = new javax.swing.JLabel();
        txt_Age = new javax.swing.JTextField();
        separtor12 = new javax.swing.JSeparator();
        message_age = new javax.swing.JLabel();
        SelectYourGender = new javax.swing.JLabel();
        rdb_Male = new javax.swing.JRadioButton();
        rdb_Female = new javax.swing.JRadioButton();
        btn_Update = new javax.swing.JButton();
        message_state = new javax.swing.JLabel();
        btn_Update1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolbar.setBackground(new java.awt.Color(255, 255, 255));
        toolbar.setAlignmentX(0.0F);
        toolbar.setAlignmentY(0.0F);
        toolbar.setPreferredSize(new java.awt.Dimension(1440, 96));
        toolbar.setLayout(new javax.swing.BoxLayout(toolbar, javax.swing.BoxLayout.X_AXIS));

        Logo.setBackground(new java.awt.Color(153, 153, 0));
        Logo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Logo.setForeground(new java.awt.Color(96, 93, 236));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Logo.setText("Flighty");
        Logo.setToolTipText("");
        Logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Logo.setPreferredSize(new java.awt.Dimension(107, 30));
        toolbar.add(Logo);

        BigSpace.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout BigSpaceLayout = new javax.swing.GroupLayout(BigSpace);
        BigSpace.setLayout(BigSpaceLayout);
        BigSpaceLayout.setHorizontalGroup(
            BigSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        BigSpaceLayout.setVerticalGroup(
            BigSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        toolbar.add(BigSpace);

        Flights.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Flights.setForeground(new java.awt.Color(124, 141, 176));
        Flights.setText("Flights");
        Flights.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlightsMouseClicked(evt);
            }
        });
        toolbar.add(Flights);

        space1.setPreferredSize(new java.awt.Dimension(15, 0));
        toolbar.add(space1);

        ManageFlights.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ManageFlights.setForeground(new java.awt.Color(124, 141, 176));
        ManageFlights.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManageFlights.setText("Manage flights");
        ManageFlights.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageFlightsMouseClicked(evt);
            }
        });
        toolbar.add(ManageFlights);

        space2.setPreferredSize(new java.awt.Dimension(15, 0));
        toolbar.add(space2);

        ManageAirports.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ManageAirports.setForeground(new java.awt.Color(124, 141, 176));
        ManageAirports.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManageAirports.setText("Manage airports");
        ManageAirports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageAirportsMouseClicked(evt);
            }
        });
        toolbar.add(ManageAirports);

        space3.setPreferredSize(new java.awt.Dimension(15, 0));
        toolbar.add(space3);

        Account.setBackground(new java.awt.Color(96, 93, 236));
        Account.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Account.setForeground(new java.awt.Color(255, 255, 255));
        Account.setText("Account");
        Account.setMaximumSize(new java.awt.Dimension(95, 48));
        Account.setPreferredSize(new java.awt.Dimension(95, 48));
        toolbar.add(Account);

        space4.setPreferredSize(new java.awt.Dimension(25, 0));
        toolbar.add(space4);

        getContentPane().add(toolbar, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlineticketbookingsystem/assets/MyAccount.png"))); // NOI18N
        body.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 140, 460, 400));

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.setPreferredSize(new java.awt.Dimension(820, 660));
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignUp1.setBackground(new java.awt.Color(0, 0, 0));
        SignUp1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SignUp1.setForeground(new java.awt.Color(96, 93, 236));
        SignUp1.setText("Account");
        LoginPanel.add(SignUp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        message_city.setForeground(new java.awt.Color(255, 0, 0));
        LoginPanel.add(message_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, -1, -1));

        message_zip.setForeground(new java.awt.Color(255, 0, 0));
        LoginPanel.add(message_zip, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        message_address.setForeground(new java.awt.Color(255, 0, 0));
        LoginPanel.add(message_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        message_confirmpassword.setForeground(new java.awt.Color(255, 0, 0));
        LoginPanel.add(message_confirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        message_password.setForeground(new java.awt.Color(255, 0, 0));
        LoginPanel.add(message_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        message_phone.setForeground(new java.awt.Color(255, 0, 0));
        LoginPanel.add(message_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        message_email.setForeground(new java.awt.Color(255, 0, 0));
        LoginPanel.add(message_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        message_lname.setForeground(new java.awt.Color(255, 0, 0));
        LoginPanel.add(message_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        EnterYourName.setBackground(new java.awt.Color(0, 0, 0));
        EnterYourName.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        EnterYourName.setForeground(new java.awt.Color(96, 93, 236));
        EnterYourName.setText("Enter Your Name");
        LoginPanel.add(EnterYourName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        message_fname.setForeground(new java.awt.Color(255, 0, 0));
        LoginPanel.add(message_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        txt_FirstName.setBackground(new java.awt.Color(255, 255, 255));
        txt_FirstName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_FirstName.setForeground(new java.awt.Color(124, 141, 176));
        txt_FirstName.setText("First Name");
        txt_FirstName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txt_FirstName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_FirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_FirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_FirstNameFocusLost(evt);
            }
        });
        LoginPanel.add(txt_FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 140, 40));

        separtor1.setForeground(new java.awt.Color(124, 141, 176));
        LoginPanel.add(separtor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 140, 10));

        txt_LastName.setBackground(new java.awt.Color(255, 255, 255));
        txt_LastName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_LastName.setForeground(new java.awt.Color(124, 141, 176));
        txt_LastName.setText("Last Name");
        txt_LastName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txt_LastName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_LastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_LastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_LastNameFocusLost(evt);
            }
        });
        LoginPanel.add(txt_LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 140, 40));

        separtor2.setForeground(new java.awt.Color(124, 141, 176));
        LoginPanel.add(separtor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 140, 10));

        EnterYourEmailAndPassword.setBackground(new java.awt.Color(0, 0, 0));
        EnterYourEmailAndPassword.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        EnterYourEmailAndPassword.setForeground(new java.awt.Color(96, 93, 236));
        EnterYourEmailAndPassword.setText("Enter Your Email and Phone");
        LoginPanel.add(EnterYourEmailAndPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        txt_Email.setEditable(false);
        txt_Email.setBackground(new java.awt.Color(255, 255, 255));
        txt_Email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Email.setForeground(new java.awt.Color(124, 141, 176));
        txt_Email.setText("Email");
        txt_Email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txt_Email.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_EmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_EmailFocusLost(evt);
            }
        });
        LoginPanel.add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 300, 40));

        separtor3.setForeground(new java.awt.Color(124, 141, 176));
        LoginPanel.add(separtor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 300, 10));

        txt_Phone.setBackground(new java.awt.Color(255, 255, 255));
        txt_Phone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Phone.setForeground(new java.awt.Color(124, 141, 176));
        txt_Phone.setText("Phone");
        txt_Phone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txt_Phone.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_Phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_PhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_PhoneFocusLost(evt);
            }
        });
        LoginPanel.add(txt_Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 300, 40));

        separtor4.setForeground(new java.awt.Color(124, 141, 176));
        LoginPanel.add(separtor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 300, 10));

        EnterYourPassword.setBackground(new java.awt.Color(0, 0, 0));
        EnterYourPassword.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        EnterYourPassword.setForeground(new java.awt.Color(96, 93, 236));
        EnterYourPassword.setText("Enter Your Password");
        LoginPanel.add(EnterYourPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        txt_Password.setBackground(new java.awt.Color(255, 255, 255));
        txt_Password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Password.setForeground(new java.awt.Color(124, 141, 176));
        txt_Password.setText("Password");
        txt_Password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txt_Password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_PasswordFocusLost(evt);
            }
        });
        LoginPanel.add(txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 300, 40));

        separtor5.setForeground(new java.awt.Color(124, 141, 176));
        LoginPanel.add(separtor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 300, 10));

        EnterYourAddress.setBackground(new java.awt.Color(0, 0, 0));
        EnterYourAddress.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        EnterYourAddress.setForeground(new java.awt.Color(96, 93, 236));
        EnterYourAddress.setText("Enter Your Address");
        LoginPanel.add(EnterYourAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        txt_Address.setBackground(new java.awt.Color(255, 255, 255));
        txt_Address.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Address.setForeground(new java.awt.Color(124, 141, 176));
        txt_Address.setText("Address");
        txt_Address.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txt_Address.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_Address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_AddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_AddressFocusLost(evt);
            }
        });
        LoginPanel.add(txt_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 300, 40));

        separtor7.setForeground(new java.awt.Color(124, 141, 176));
        LoginPanel.add(separtor7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 300, 10));

        txt_Zip.setBackground(new java.awt.Color(255, 255, 255));
        txt_Zip.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Zip.setForeground(new java.awt.Color(124, 141, 176));
        txt_Zip.setText("Zip/Postal");
        txt_Zip.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txt_Zip.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_Zip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_ZipFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_ZipFocusLost(evt);
            }
        });
        LoginPanel.add(txt_Zip, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 140, 40));

        separtor8.setForeground(new java.awt.Color(124, 141, 176));
        LoginPanel.add(separtor8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 140, 10));

        txt_City.setBackground(new java.awt.Color(255, 255, 255));
        txt_City.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_City.setForeground(new java.awt.Color(124, 141, 176));
        txt_City.setText("City");
        txt_City.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txt_City.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_City.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_CityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_CityFocusLost(evt);
            }
        });
        LoginPanel.add(txt_City, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 140, 40));

        separtor9.setForeground(new java.awt.Color(124, 141, 176));
        LoginPanel.add(separtor9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 140, 10));

        txt_State.setBackground(new java.awt.Color(255, 255, 255));
        txt_State.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_State.setForeground(new java.awt.Color(124, 141, 176));
        txt_State.setText("State");
        txt_State.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txt_State.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_State.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_StateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_StateFocusLost(evt);
            }
        });
        LoginPanel.add(txt_State, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 140, 40));

        separtor10.setForeground(new java.awt.Color(124, 141, 176));
        LoginPanel.add(separtor10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 140, 10));

        txt_Country.setBackground(new java.awt.Color(255, 255, 255));
        txt_Country.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Country.setForeground(new java.awt.Color(124, 141, 176));
        txt_Country.setText("Country");
        txt_Country.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txt_Country.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_Country.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_CountryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_CountryFocusLost(evt);
            }
        });
        LoginPanel.add(txt_Country, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 140, 40));

        separtor11.setForeground(new java.awt.Color(124, 141, 176));
        LoginPanel.add(separtor11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 140, 10));

        message_country.setForeground(new java.awt.Color(255, 0, 0));
        LoginPanel.add(message_country, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, -1, -1));

        EnterYourAge.setBackground(new java.awt.Color(0, 0, 0));
        EnterYourAge.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        EnterYourAge.setForeground(new java.awt.Color(96, 93, 236));
        EnterYourAge.setText("Enter Your Age");
        LoginPanel.add(EnterYourAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, -1, -1));

        txt_Age.setBackground(new java.awt.Color(255, 255, 255));
        txt_Age.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Age.setForeground(new java.awt.Color(124, 141, 176));
        txt_Age.setText("Age");
        txt_Age.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txt_Age.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_Age.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_AgeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_AgeFocusLost(evt);
            }
        });
        LoginPanel.add(txt_Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 80, 40));

        separtor12.setForeground(new java.awt.Color(124, 141, 176));
        LoginPanel.add(separtor12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 80, 10));

        message_age.setForeground(new java.awt.Color(255, 0, 0));
        LoginPanel.add(message_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, -1));

        SelectYourGender.setBackground(new java.awt.Color(0, 0, 0));
        SelectYourGender.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        SelectYourGender.setForeground(new java.awt.Color(96, 93, 236));
        SelectYourGender.setText("Select Your Gender");
        LoginPanel.add(SelectYourGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, -1, -1));

        rdb_Male.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdb_Male);
        rdb_Male.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdb_Male.setForeground(new java.awt.Color(124, 141, 176));
        rdb_Male.setSelected(true);
        rdb_Male.setText("Male");
        LoginPanel.add(rdb_Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, -1, -1));

        rdb_Female.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdb_Female);
        rdb_Female.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdb_Female.setForeground(new java.awt.Color(124, 141, 176));
        rdb_Female.setText("Female");
        LoginPanel.add(rdb_Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, -1, -1));

        btn_Update.setBackground(new java.awt.Color(96, 93, 236));
        btn_Update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Update.setForeground(new java.awt.Color(255, 255, 255));
        btn_Update.setText("Update");
        btn_Update.setPreferredSize(new java.awt.Dimension(95, 48));
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });
        LoginPanel.add(btn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 120, -1));

        message_state.setForeground(new java.awt.Color(255, 0, 0));
        LoginPanel.add(message_state, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        btn_Update1.setBackground(new java.awt.Color(124, 141, 176));
        btn_Update1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Update1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Update1.setText("Logout");
        btn_Update1.setPreferredSize(new java.awt.Dimension(95, 48));
        btn_Update1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Update1MouseClicked(evt);
            }
        });
        LoginPanel.add(btn_Update1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 120, -1));

        body.add(LoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 590));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlineticketbookingsystem/assets/WorldMap.png"))); // NOI18N
        body.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 700));

        getContentPane().add(body, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FlightsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlightsMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new AdminHomePage().setVisible(true);
    }//GEN-LAST:event_FlightsMouseClicked

    private void ManageFlightsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageFlightsMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new ManageFlightsPage().setVisible(true);
    }//GEN-LAST:event_ManageFlightsMouseClicked

    private void ManageAirportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageAirportsMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new ManageAirportsPage().setVisible(true);
    }//GEN-LAST:event_ManageAirportsMouseClicked

    private void txt_FirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_FirstNameFocusGained
        // TODO add your handling code here:

        if (txt_FirstName.getText().equals("First Name")) {
            txt_FirstName.setText("");
        }
        message_fname.setVisible(false);
    }//GEN-LAST:event_txt_FirstNameFocusGained

    private void txt_FirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_FirstNameFocusLost
        // TODO add your handling code here:
        if (txt_FirstName.getText().length()==0) {
            txt_FirstName.setText("First Name");
        }
    }//GEN-LAST:event_txt_FirstNameFocusLost

    private void txt_LastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_LastNameFocusGained
        // TODO add your handling code here:
        if (txt_LastName.getText().equals("Last Name")) {
            txt_LastName.setText("");
        }
        message_lname.setVisible(false);
    }//GEN-LAST:event_txt_LastNameFocusGained

    private void txt_LastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_LastNameFocusLost
        // TODO add your handling code here:
        if (txt_LastName.getText().length()==0) {
            txt_LastName.setText("Last Name");
        }
    }//GEN-LAST:event_txt_LastNameFocusLost

    private void txt_EmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_EmailFocusGained
        // TODO add your handling code here:
        if (txt_Email.getText().equals("Email")) {
            txt_Email.setText("");
        }
        message_email.setVisible(false);
    }//GEN-LAST:event_txt_EmailFocusGained

    private void txt_EmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_EmailFocusLost
        // TODO add your handling code here:
        if (txt_Email.getText().length()==0) {
            txt_Email.setText("Email");
        }
    }//GEN-LAST:event_txt_EmailFocusLost

    private void txt_PhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PhoneFocusGained
        // TODO add your handling code here:
        if (txt_Phone.getText().equals("Phone")) {
            txt_Phone.setText("");
        }
        message_phone.setVisible(false);
    }//GEN-LAST:event_txt_PhoneFocusGained

    private void txt_PhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PhoneFocusLost
        // TODO add your handling code here:
        if (txt_Phone.getText().length()==0) {
            txt_Phone.setText("Phone");
        }
    }//GEN-LAST:event_txt_PhoneFocusLost

    private void txt_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PasswordFocusGained
        // TODO add your handling code here:
        if (txt_Password.getText().equals("Password")) {
            txt_Password.setText("");
        }
        message_password.setVisible(false);
    }//GEN-LAST:event_txt_PasswordFocusGained

    private void txt_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PasswordFocusLost
        // TODO add your handling code here:
        if (txt_Password.getText().length()==0) {
            txt_Password.setText("Password");
        }
    }//GEN-LAST:event_txt_PasswordFocusLost

    private void txt_AddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_AddressFocusGained
        // TODO add your handling code here:
        if (txt_Address.getText().equals("Address")) {
            txt_Address.setText("");
        }
        message_address.setVisible(false);
    }//GEN-LAST:event_txt_AddressFocusGained

    private void txt_AddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_AddressFocusLost
        // TODO add your handling code here:
        if (txt_Address.getText().length()==0) {
            txt_Address.setText("Address");
        }
    }//GEN-LAST:event_txt_AddressFocusLost

    private void txt_ZipFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ZipFocusGained
        // TODO add your handling code here:
        if (txt_Zip.getText().equals("Zip/Postal")) {
            txt_Zip.setText("");
        }
        message_zip.setVisible(false);
    }//GEN-LAST:event_txt_ZipFocusGained

    private void txt_ZipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ZipFocusLost
        // TODO add your handling code here:
        if (txt_Zip.getText().length()==0) {
            txt_Zip.setText("Zip/Postal");
        }
    }//GEN-LAST:event_txt_ZipFocusLost

    private void txt_CityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CityFocusGained
        // TODO add your handling code here:
        if (txt_City.getText().equals("City")) {
            txt_City.setText("");
        }
        message_city.setVisible(false);
    }//GEN-LAST:event_txt_CityFocusGained

    private void txt_CityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CityFocusLost
        // TODO add your handling code here:
        if (txt_City.getText().length()==0) {
            txt_City.setText("City");
        }
    }//GEN-LAST:event_txt_CityFocusLost

    private void txt_StateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_StateFocusGained
        // TODO add your handling code here:
        if (txt_State.getText().equals("State")) {
            txt_State.setText("");
        }
        message_state.setVisible(false);
    }//GEN-LAST:event_txt_StateFocusGained

    private void txt_StateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_StateFocusLost
        // TODO add your handling code here:
        if (txt_State.getText().length()==0) {
            txt_State.setText("State");
        }
    }//GEN-LAST:event_txt_StateFocusLost

    private void txt_CountryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CountryFocusGained
        // TODO add your handling code here:
        if (txt_Country.getText().equals("Country")) {
            txt_Country.setText("");
        }
        message_country.setVisible(false);
    }//GEN-LAST:event_txt_CountryFocusGained

    private void txt_CountryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CountryFocusLost
        // TODO add your handling code here:
        if (txt_Country.getText().length()==0) {
            txt_Country.setText("Country");
        }
    }//GEN-LAST:event_txt_CountryFocusLost

    private void txt_AgeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_AgeFocusGained
        // TODO add your handling code here:
        if (txt_Age.getText().equals("Age")) {
            txt_Age.setText("");
        }
        message_age.setVisible(false);
    }//GEN-LAST:event_txt_AgeFocusGained

    private void txt_AgeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_AgeFocusLost
        // TODO add your handling code here:
        if (txt_Age.getText().length()==0) {
            txt_Age.setText("Age");
        }
    }//GEN-LAST:event_txt_AgeFocusLost

    private boolean checkFirstName() {
        if (fName.isEmpty() || fName.equals("First Name")) {
            message_fname.setText("*Enter first name");
            message_fname.setVisible(true);
            return false;
        }
        if (fName.length() < 2) {
            message_fname.setText("*First name is too short");
            message_fname.setVisible(true);
            return false;
        }
        return true;
    }

    private boolean checkLastName() {
        if (lName.isEmpty() || lName.equals("Last Name")) {
            message_lname.setText("*Enter last name");
            message_lname.setVisible(true);
            return false;
        }
        if (lName.length() < 2) {
            message_lname.setText("*Last name is too short");
            message_lname.setVisible(true);
            return false;
        }
        return true;
    }

    private boolean checkEmail() {
        if (email.isEmpty() || email.equals("Email")) {
            message_email.setText("*Enter email");
            message_email.setVisible(true);
            return false;
        }
        if (!email.contains("@gmail.com")) {
            message_email.setText("*Enter valid email");
            message_email.setVisible(true);
            return false;
        }
        return true;
    }
    
    private boolean checkPhone() {
        if (phone.isEmpty() || phone.equals("Phone")) {
            message_phone.setText("*Enter phone number");
            message_phone.setVisible(true);
            return false;
        }
        if (!phone.matches("\\d{10,15}")) {
            message_phone.setText("*Enter a valid phone number");
            message_phone.setVisible(true);
            return false;
        }
        return true;
    }

    private boolean checkPassword() {
        if (password.isEmpty() || password.equals("Password")) {
            message_password.setText("*Enter password");
            message_password.setVisible(true);
            return false;
        }
        if (password.length() < 8) {
            message_password.setText("*Password must be at least 8 characters");
            message_password.setVisible(true);
            return false;
        }
        return true;
    }

    private boolean checkAddress() {
        if (address.isEmpty() || address.equals("Address")) {
            message_address.setText("*Enter address");
            message_address.setVisible(true);
            return false;
        }
        return true;
    }

    private boolean checkZip() {
        if (zip.isEmpty() || zip.equals("Zip/Postal")) {
            message_zip.setText("*Enter zip code");
            message_zip.setVisible(true);
            return false;
        }
        if (!zip.matches("\\d{4,10}")) {
            message_zip.setText("*Enter a valid zip code");
            message_zip.setVisible(true);
            return false;
        }
        return true;
    }

    private boolean checkCity() {
        if (city.isEmpty() || city.equals("City")) {
            message_city.setText("*Enter city");
            message_city.setVisible(true);
            return false;
        }
        return true;
    }

    private boolean checkState() {
        if (state.isEmpty() || state.equals("State")) {
            message_state.setText("*Enter state");
            message_state.setVisible(true);
            return false;
        }
        return true;
    }

    private boolean checkCountry() {
        if (country.isEmpty() || country.equals("Country")) {
            message_country.setText("*Enter country");
            message_country.setVisible(true);
            return false;
        }
        return true;
    }

    private boolean checkAge() {
        if (sage.isEmpty() || sage.equals("Age")) {
            message_age.setText("*Enter age");
            message_age.setVisible(true);
            return false;
        }
        if (!sage.matches("\\d{1,3}")) {
            message_age.setText("*Enter a valid age");
            message_age.setVisible(true);
            return false;
        }
        age = Integer.parseInt(sage);
        if (age <= 17 || age > 120) {
            message_age.setText("*Enter a valid age");
            message_age.setVisible(true);
            return false;
        }
        return true;
    }
    
    private void btnclc() {
        cfName = cur.getFirstName();
        clName = cur.getLastName();
        cemail = cur.getEmail();
        cphone = cur.getPhone();
        cpassword = cur.getPassword();
        caddress = cur.getAddress();
        czip = cur.getZip();
        ccity = cur.getCity();
        cstate = cur.getState();
        ccountry = cur.getCountry();
        cage = cur.getAge();
        cgender = cur.getGender();
        
        txt_FirstName.setText(cfName);
        txt_LastName.setText(clName);
        txt_Email.setText(cemail);
        txt_Phone.setText(cphone);
        txt_Password.setText(cpassword);
        txt_Address.setText(caddress);
        txt_Zip.setText(czip);
        txt_City.setText(ccity);
        txt_State.setText(cstate);
        txt_Country.setText(ccountry);
        txt_Age.setText(String.valueOf(cage));
        if (cgender.equals("Male")) rdb_Male.setSelected(true);
        else rdb_Female.setSelected(true);
    }
    
    private boolean checkchanges() {
        return !(fName.equals(cfName) &&
                lName.equals(clName) &&
                email.equals(cemail) &&
                phone.equals(cphone) &&
                password.equals(cpassword) &&
                address.equals(caddress) &&
                zip.equals(czip) &&
                city.equals(ccity) &&
                state.equals(cstate) &&
                country.equals(ccountry) &&
                String.valueOf(age).equals(String.valueOf(cage)) &&
                gender.equals(cgender));
    }
    
    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // TODO add your handling code here:
//        btnclc();
        fName = txt_FirstName.getText();
        lName = txt_LastName.getText();
        email = txt_Email.getText();
        phone = txt_Phone.getText();
        password = txt_Password.getText();
        address = txt_Address.getText();
        zip = txt_Zip.getText();
        city = txt_City.getText();
        state = txt_State.getText();
        country = txt_Country.getText();
        sage = txt_Age.getText();
        if (rdb_Male.isSelected()) gender = "Male";
        else gender = "Female";
        
        
        boolean isValid = true;
        if (!checkFirstName()) isValid = false; if (!checkLastName()) isValid = false; if (!checkEmail()) isValid = false;
        if (!checkPhone()) isValid = false; if (!checkPassword()) isValid = false; if (!checkAddress()) isValid = false;
        if (!checkZip()) isValid = false; if (!checkCity()) isValid = false; if (!checkState()) isValid = false; if (!checkCountry()) isValid = false; if (!checkAge()) isValid = false;
        if (!checkchanges()) {
            isValid = false;
            JOptionPane.showMessageDialog(null, "You made no changes");
        }
        if (!isValid) {
            System.out.println("Validation failed");
            return;
        }
        
        System.out.println("Validation successful");
        user.setRole(cur.getRole());
        user.setFirstName(fName);
        user.setLastName(lName);
        user.setEmail(email);
        user.setPhone(phone);
        user.setPassword(password);
        user.setAddress(address);
        user.setZip(zip);
        user.setCity(city);
        user.setState(state);
        user.setCountry(country);
        user.setAge(age);
        user.setGender(gender);
        AppSession.setCurrentUser(user);
        userDAO.updateUser(user);
        JOptionPane.showMessageDialog(null, "Account updated Successfully");
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btn_Update1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Update1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new MainPage().setVisible(true);
    }//GEN-LAST:event_btn_Update1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("default".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountAdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Account;
    private javax.swing.JPanel BigSpace;
    private javax.swing.JLabel EnterYourAddress;
    private javax.swing.JLabel EnterYourAge;
    private javax.swing.JLabel EnterYourEmailAndPassword;
    private javax.swing.JLabel EnterYourName;
    private javax.swing.JLabel EnterYourPassword;
    private javax.swing.JLabel Flights;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel ManageAirports;
    private javax.swing.JLabel ManageFlights;
    private javax.swing.JLabel SelectYourGender;
    private javax.swing.JLabel SignUp1;
    private javax.swing.JLabel background;
    private javax.swing.JPanel body;
    private javax.swing.JButton btn_Update;
    private javax.swing.JButton btn_Update1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel message_address;
    private javax.swing.JLabel message_age;
    private javax.swing.JLabel message_city;
    private javax.swing.JLabel message_confirmpassword;
    private javax.swing.JLabel message_country;
    private javax.swing.JLabel message_email;
    private javax.swing.JLabel message_fname;
    private javax.swing.JLabel message_lname;
    private javax.swing.JLabel message_password;
    private javax.swing.JLabel message_phone;
    private javax.swing.JLabel message_state;
    private javax.swing.JLabel message_zip;
    private javax.swing.JRadioButton rdb_Female;
    private javax.swing.JRadioButton rdb_Male;
    private javax.swing.JSeparator separtor1;
    private javax.swing.JSeparator separtor10;
    private javax.swing.JSeparator separtor11;
    private javax.swing.JSeparator separtor12;
    private javax.swing.JSeparator separtor2;
    private javax.swing.JSeparator separtor3;
    private javax.swing.JSeparator separtor4;
    private javax.swing.JSeparator separtor5;
    private javax.swing.JSeparator separtor7;
    private javax.swing.JSeparator separtor8;
    private javax.swing.JSeparator separtor9;
    private javax.swing.JLabel space1;
    private javax.swing.JLabel space2;
    private javax.swing.JLabel space3;
    private javax.swing.JLabel space4;
    private javax.swing.JPanel toolbar;
    private javax.swing.JTextField txt_Address;
    private javax.swing.JTextField txt_Age;
    private javax.swing.JTextField txt_City;
    private javax.swing.JTextField txt_Country;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_FirstName;
    private javax.swing.JTextField txt_LastName;
    private javax.swing.JTextField txt_Password;
    private javax.swing.JTextField txt_Phone;
    private javax.swing.JTextField txt_State;
    private javax.swing.JTextField txt_Zip;
    // End of variables declaration//GEN-END:variables
}
