/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airlineticketbookingsystem.Pages;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import airlineticketbookingsystem.dbconnection.*;
import airlineticketbookingsystem.models.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author taake
 */
public class AdminHomePage extends javax.swing.JFrame {
    DefaultTableModel dtm;
    FlightsDAO flightDAO = new FlightsDAO();
    List<Flight> flights;
    public AdminHomePage() {
        initComponents();
        this.setLocationRelativeTo(null);
        delete_btn.setVisible(false);
        flight_tbl.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        flight_tbl.getTableHeader().setBackground(new Color(184, 183, 240));
        flight_tbl.getTableHeader().setForeground(Color.black);
        flight_tbl.getTableHeader().setPreferredSize(new Dimension(flight_tbl.getColumnModel().getTotalColumnWidth(), 40));
        flight_tbl.setGridColor(Color.black);
        flight_tbl.setBackground(Color.white);
        dtm = new DefaultTableModel();
        dtm.addColumn("Flight name");
        dtm.addColumn("Source");
        dtm.addColumn("Destination");
        dtm.addColumn("Date");
        dtm.addColumn("Time");
        fillflight_tbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        BigSpace = new javax.swing.JPanel();
        Flights = new javax.swing.JLabel();
        space1 = new javax.swing.JLabel();
        ManageFlights = new javax.swing.JLabel();
        space2 = new javax.swing.JLabel();
        ManageAirports = new javax.swing.JLabel();
        space3 = new javax.swing.JLabel();
        Account = new javax.swing.JButton();
        space4 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        table_panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        flight_tbl = new javax.swing.JTable();
        delete_btn = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolbar.setBackground(new java.awt.Color(255, 255, 255));
        toolbar.setAlignmentX(0.0F);
        toolbar.setAlignmentY(0.0F);
        toolbar.setPreferredSize(new java.awt.Dimension(1440, 96));
        toolbar.setLayout(new javax.swing.BoxLayout(toolbar, javax.swing.BoxLayout.X_AXIS));

        Logo.setBackground(new java.awt.Color(153, 153, 0));
        Logo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Logo.setForeground(new java.awt.Color(96, 93, 236));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Logo.setText("Flighty");
        Logo.setToolTipText("");
        Logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Logo.setPreferredSize(new java.awt.Dimension(107, 30));
        toolbar.add(Logo);

        BigSpace.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout BigSpaceLayout = new javax.swing.GroupLayout(BigSpace);
        BigSpace.setLayout(BigSpaceLayout);
        BigSpaceLayout.setHorizontalGroup(
            BigSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        BigSpaceLayout.setVerticalGroup(
            BigSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        toolbar.add(BigSpace);

        Flights.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Flights.setForeground(new java.awt.Color(96, 93, 236));
        Flights.setText("Flights");
        toolbar.add(Flights);

        space1.setPreferredSize(new java.awt.Dimension(15, 0));
        toolbar.add(space1);

        ManageFlights.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ManageFlights.setForeground(new java.awt.Color(124, 141, 176));
        ManageFlights.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManageFlights.setText("Manage flights");
        ManageFlights.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageFlightsMouseClicked(evt);
            }
        });
        toolbar.add(ManageFlights);

        space2.setPreferredSize(new java.awt.Dimension(15, 0));
        toolbar.add(space2);

        ManageAirports.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ManageAirports.setForeground(new java.awt.Color(124, 141, 176));
        ManageAirports.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManageAirports.setText("Manage airports");
        ManageAirports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageAirportsMouseClicked(evt);
            }
        });
        toolbar.add(ManageAirports);

        space3.setPreferredSize(new java.awt.Dimension(15, 0));
        toolbar.add(space3);

        Account.setBackground(new java.awt.Color(96, 93, 236));
        Account.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Account.setForeground(new java.awt.Color(255, 255, 255));
        Account.setText("Account");
        Account.setMaximumSize(new java.awt.Dimension(95, 48));
        Account.setPreferredSize(new java.awt.Dimension(95, 48));
        Account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountMouseClicked(evt);
            }
        });
        toolbar.add(Account);

        space4.setPreferredSize(new java.awt.Dimension(25, 0));
        toolbar.add(space4);

        getContentPane().add(toolbar, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_panel.setBackground(new java.awt.Color(255, 255, 255));

        flight_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Flight name", "Source", "Destination", "Date", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        flight_tbl.setRowHeight(38);
        flight_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flight_tblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(flight_tbl);

        javax.swing.GroupLayout table_panelLayout = new javax.swing.GroupLayout(table_panel);
        table_panel.setLayout(table_panelLayout);
        table_panelLayout.setHorizontalGroup(
            table_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        table_panelLayout.setVerticalGroup(
            table_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        body.add(table_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 220, 920, 210));

        delete_btn.setBackground(new java.awt.Color(124, 141, 176));
        delete_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(255, 255, 255));
        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        body.add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, 100, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlineticketbookingsystem/assets/WorldMap.png"))); // NOI18N
        body.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 700));

        getContentPane().add(body, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillflight_tbl() {
        flights = flightDAO.getAllFlights();
        dtm.setRowCount(0);
        for (Flight flight : flights) {
            String fName = flight.getFlightName();
            String fSource = flight.getSource();
            String fDestination = flight.getDestination();
            String fDate = flight.getDate();
            String fTime = flight.getTime();
            dtm.addRow(new Object[]{fName, fSource, fDestination, fDate, fTime});
        }
        flight_tbl.setModel(dtm);
    }
    
    
    private void AccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new AccountAdminPage().setVisible(true);
    }//GEN-LAST:event_AccountMouseClicked

    private void ManageAirportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageAirportsMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new ManageAirportsPage().setVisible(true);
    }//GEN-LAST:event_ManageAirportsMouseClicked

    private void ManageFlightsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageFlightsMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new ManageFlightsPage().setVisible(true);
    }//GEN-LAST:event_ManageFlightsMouseClicked

    private void flight_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flight_tblMouseClicked
        // TODO add your handling code here:
        flight_tbl.getValueAt(flight_tbl.getSelectedRow(), flight_tbl.getSelectedColumn());
        AppSession.setcurrentFlight(flights.get(flight_tbl.getSelectedRow()));
        Flight fl = AppSession.getcurrentFlight();
        System.out.println(fl.getId());
        delete_btn.setVisible(true);
    }//GEN-LAST:event_flight_tblMouseClicked

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(
            null,
            "Are you sure you want to delete this item?",
            "Delete Confirmation",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        if (choice == JOptionPane.YES_OPTION) {
            Flight f = flights.get(flight_tbl.getSelectedRow());
            flightDAO.deleteFlight(f.getId());
            System.out.println("Item deleted successfully.");
            fillflight_tbl();
        } else {
            System.out.println("Deletion cancelled.");
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("default".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Account;
    private javax.swing.JPanel BigSpace;
    private javax.swing.JLabel Flights;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel ManageAirports;
    private javax.swing.JLabel ManageFlights;
    private javax.swing.JLabel background;
    private javax.swing.JPanel body;
    private javax.swing.JButton delete_btn;
    private javax.swing.JTable flight_tbl;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel space1;
    private javax.swing.JLabel space2;
    private javax.swing.JLabel space3;
    private javax.swing.JLabel space4;
    private javax.swing.JPanel table_panel;
    private javax.swing.JPanel toolbar;
    // End of variables declaration//GEN-END:variables
}
