/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airlineticketbookingsystem.Pages;

import airlineticketbookingsystem.dbconnection.AirportsDAO;
import airlineticketbookingsystem.dbconnection.FlightsDAO;
import airlineticketbookingsystem.dbconnection.UserDAO;
import airlineticketbookingsystem.models.Airport;
import airlineticketbookingsystem.models.AppSession;
import airlineticketbookingsystem.models.Flight;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class BookedPage extends javax.swing.JFrame {
    DefaultTableModel dtm;
    AirportsDAO airportDAO = new AirportsDAO();
    List<Airport> airports = airportDAO.getAllAirports();
    UserDAO userDAO = new UserDAO();
    FlightsDAO flightDAO = new FlightsDAO();
    List<Flight> flights;
    public BookedPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        cancel_btn.setVisible(false);
        flight_tbl.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        flight_tbl.getTableHeader().setBackground(new Color(184, 183, 240));
        flight_tbl.getTableHeader().setForeground(Color.black);
        flight_tbl.getTableHeader().setPreferredSize(new Dimension(flight_tbl.getColumnModel().getTotalColumnWidth(), 40));
        flight_tbl.setGridColor(Color.black);
        flight_tbl.setBackground(Color.white);
        
        dtm = new DefaultTableModel();
        dtm.addColumn("Flight name");
        dtm.addColumn("Source");
        dtm.addColumn("Destination");
        dtm.addColumn("Price");
        dtm.addColumn("Date");
        dtm.addColumn("Time");
        dtm.addColumn("Business seat");
        dtm.addColumn("Economic seat");
        fillflight_tbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        BigSpace = new javax.swing.JPanel();
        Flights = new javax.swing.JLabel();
        space1 = new javax.swing.JLabel();
        Booked = new javax.swing.JLabel();
        space2 = new javax.swing.JLabel();
        Account = new javax.swing.JButton();
        space3 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        flight_tbl = new javax.swing.JTable();
        cancel_btn = new javax.swing.JButton();
        lbl_BookFlight = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolbar.setBackground(new java.awt.Color(255, 255, 255));
        toolbar.setAlignmentX(0.0F);
        toolbar.setAlignmentY(0.0F);
        toolbar.setPreferredSize(new java.awt.Dimension(1440, 96));
        toolbar.setLayout(new javax.swing.BoxLayout(toolbar, javax.swing.BoxLayout.X_AXIS));

        Logo.setBackground(new java.awt.Color(153, 153, 0));
        Logo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Logo.setForeground(new java.awt.Color(96, 93, 236));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Logo.setText("Flighty");
        Logo.setToolTipText("");
        Logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Logo.setPreferredSize(new java.awt.Dimension(107, 30));
        toolbar.add(Logo);

        BigSpace.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout BigSpaceLayout = new javax.swing.GroupLayout(BigSpace);
        BigSpace.setLayout(BigSpaceLayout);
        BigSpaceLayout.setHorizontalGroup(
            BigSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1085, Short.MAX_VALUE)
        );
        BigSpaceLayout.setVerticalGroup(
            BigSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        toolbar.add(BigSpace);

        Flights.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Flights.setForeground(new java.awt.Color(124, 141, 176));
        Flights.setText("Flights");
        Flights.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlightsMouseClicked(evt);
            }
        });
        toolbar.add(Flights);

        space1.setPreferredSize(new java.awt.Dimension(15, 0));
        toolbar.add(space1);

        Booked.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Booked.setForeground(new java.awt.Color(96, 93, 236));
        Booked.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Booked.setText("Booked");
        toolbar.add(Booked);

        space2.setPreferredSize(new java.awt.Dimension(15, 0));
        toolbar.add(space2);

        Account.setBackground(new java.awt.Color(96, 93, 236));
        Account.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Account.setForeground(new java.awt.Color(255, 255, 255));
        Account.setText("Account");
        Account.setMaximumSize(new java.awt.Dimension(95, 48));
        Account.setPreferredSize(new java.awt.Dimension(95, 48));
        Account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountMouseClicked(evt);
            }
        });
        toolbar.add(Account);

        space3.setPreferredSize(new java.awt.Dimension(25, 0));
        toolbar.add(space3);

        getContentPane().add(toolbar, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setPreferredSize(new java.awt.Dimension(1140, 700));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        flight_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Flight Name", "Source", "Destination", "Price", "Date", "Time", "Business seat", "Economic seat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        flight_tbl.setRowHeight(40);
        flight_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flight_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(flight_tbl);

        body.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 152, 1128, 240));

        cancel_btn.setBackground(new java.awt.Color(96, 93, 236));
        cancel_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancel_btn.setForeground(new java.awt.Color(255, 255, 255));
        cancel_btn.setText("Cancel Flight");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });
        body.add(cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, -1, 37));

        lbl_BookFlight.setBackground(new java.awt.Color(0, 0, 0));
        lbl_BookFlight.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_BookFlight.setForeground(new java.awt.Color(96, 93, 236));
        lbl_BookFlight.setText("Booked Flight");
        body.add(lbl_BookFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlineticketbookingsystem/assets/WorldMap.png"))); // NOI18N
        body.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 700));

        getContentPane().add(body, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillflight_tbl() {
        flights = userDAO.getPreviousFlights(AppSession.getCurrentUser().getId());
        dtm.setRowCount(0);
        for (Flight flight : flights) {
            String fName = flight.getFlightName();
            String fSource = flight.getSource();
            String fDestination = flight.getDestination();
            String fDate = flight.getDate();
            String fTime = flight.getTime();
            int bseat = flight.getBusinessSeat();
            int eseat = flight.getEconomySeat();
            int bnum = flight.getBagNumber();
            int price = airportDAO.getAirportPrice(fSource) + airportDAO.getAirportPrice(fDestination) + (200 * bseat) + (100 * eseat) + (50 *bnum);
            dtm.addRow(new Object[]{fName, fSource, fDestination, price, fDate, fTime, bseat, eseat, bnum});
        }
        flight_tbl.setModel(dtm);
    }
    
    private void FlightsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlightsMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new UserHomePage().setVisible(true);
    }//GEN-LAST:event_FlightsMouseClicked

    private void AccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new AccountUserPage().setVisible(true);
    }//GEN-LAST:event_AccountMouseClicked

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        // TODO add your handling code here:
        int idx = flight_tbl.getSelectedRow();
        Flight flight = flights.get(idx);
        int id = flight.getId();
        int uid = AppSession.getCurrentUser().getId();
        userDAO.deleteUserFlight(uid, id);
        fillflight_tbl();
        JOptionPane.showMessageDialog(null, "Flight canceled Successfully");
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void flight_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flight_tblMouseClicked
        // TODO add your handling code here:
        cancel_btn.setVisible(true);
    }//GEN-LAST:event_flight_tblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("default".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookedPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Account;
    private javax.swing.JPanel BigSpace;
    private javax.swing.JLabel Booked;
    private javax.swing.JLabel Flights;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel background;
    private javax.swing.JPanel body;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JTable flight_tbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_BookFlight;
    private javax.swing.JLabel space1;
    private javax.swing.JLabel space2;
    private javax.swing.JLabel space3;
    private javax.swing.JPanel toolbar;
    // End of variables declaration//GEN-END:variables
}
