/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airlineticketbookingsystem.Pages;

import airlineticketbookingsystem.dbconnection.*;
import airlineticketbookingsystem.models.*;
import airlineticketbookingsystem.models.AppSession;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author taake
 */
public class BookPage extends javax.swing.JFrame {
    Flight cur = AppSession.getcurrentFlight();
    AirportsDAO airportDAO = new AirportsDAO();
    UserDAO userDAO = new UserDAO();
    int sprice, dprice, pnum, eenum, bnum;
    public BookPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        txt_FlightName.setText(cur.getFlightName());
        txt_Source.setText(cur.getSource());
        txt_Destination.setText(cur.getDestination());
        txt_Date.setText(cur.getDate());
        txt_Time.setText(cur.getTime());
        sprice = airportDAO.getAirportPrice(cur.getSource());
        dprice = airportDAO.getAirportPrice(cur.getDestination());
        int total = sprice + dprice + 100;
        txt_Price.setText(String.valueOf(total));
    }

    private void updateprice() {
        int total = dprice + sprice;
        pnum = Integer.parseInt(spn_BusinessSeat.getValue().toString());
        eenum = Integer.parseInt(spn_EconomicSeat.getValue().toString());
        bnum = Integer.parseInt(spn_BagNumber.getValue().toString());
        total += (200 * pnum) + (100 * eenum) + (50 * bnum); 
        txt_Price.setText(String.valueOf(total));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        BigSpace = new javax.swing.JPanel();
        Flights = new javax.swing.JLabel();
        space1 = new javax.swing.JLabel();
        Booked = new javax.swing.JLabel();
        space2 = new javax.swing.JLabel();
        Account = new javax.swing.JButton();
        space3 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        lbl_BookFlight = new javax.swing.JLabel();
        lbl_FlightName = new javax.swing.JLabel();
        txt_FlightName = new javax.swing.JLabel();
        lbl_Source = new javax.swing.JLabel();
        txt_Source = new javax.swing.JLabel();
        lbl_Destination = new javax.swing.JLabel();
        txt_Destination = new javax.swing.JLabel();
        txt_Date = new javax.swing.JLabel();
        lbl_Time = new javax.swing.JLabel();
        txt_Time = new javax.swing.JLabel();
        lbl_Date = new javax.swing.JLabel();
        lbl_BusinessSeat = new javax.swing.JLabel();
        spn_BusinessSeat = new javax.swing.JSpinner();
        lbl_EconomicSeat = new javax.swing.JLabel();
        spn_EconomicSeat = new javax.swing.JSpinner();
        lbl_BagNumber = new javax.swing.JLabel();
        spn_BagNumber = new javax.swing.JSpinner();
        lbl_Price = new javax.swing.JLabel();
        txt_Price = new javax.swing.JLabel();
        btn_BoolFlight = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolbar.setBackground(new java.awt.Color(255, 255, 255));
        toolbar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(124, 141, 176), 1, true));
        toolbar.setAlignmentX(0.0F);
        toolbar.setAlignmentY(0.0F);
        toolbar.setPreferredSize(new java.awt.Dimension(1440, 96));
        toolbar.setLayout(new javax.swing.BoxLayout(toolbar, javax.swing.BoxLayout.X_AXIS));

        Logo.setBackground(new java.awt.Color(153, 153, 0));
        Logo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Logo.setForeground(new java.awt.Color(96, 93, 236));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Logo.setText("Flighty");
        Logo.setToolTipText("");
        Logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Logo.setPreferredSize(new java.awt.Dimension(107, 30));
        toolbar.add(Logo);

        BigSpace.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout BigSpaceLayout = new javax.swing.GroupLayout(BigSpace);
        BigSpace.setLayout(BigSpaceLayout);
        BigSpaceLayout.setHorizontalGroup(
            BigSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1083, Short.MAX_VALUE)
        );
        BigSpaceLayout.setVerticalGroup(
            BigSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        toolbar.add(BigSpace);

        Flights.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Flights.setForeground(new java.awt.Color(124, 141, 176));
        Flights.setText("Flights");
        Flights.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlightsMouseClicked(evt);
            }
        });
        toolbar.add(Flights);

        space1.setPreferredSize(new java.awt.Dimension(15, 0));
        toolbar.add(space1);

        Booked.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Booked.setForeground(new java.awt.Color(124, 141, 176));
        Booked.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Booked.setText("Booked");
        Booked.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookedMouseClicked(evt);
            }
        });
        toolbar.add(Booked);

        space2.setPreferredSize(new java.awt.Dimension(15, 0));
        toolbar.add(space2);

        Account.setBackground(new java.awt.Color(96, 93, 236));
        Account.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Account.setForeground(new java.awt.Color(255, 255, 255));
        Account.setText("Account");
        Account.setMaximumSize(new java.awt.Dimension(95, 48));
        Account.setPreferredSize(new java.awt.Dimension(95, 48));
        Account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountMouseClicked(evt);
            }
        });
        toolbar.add(Account);

        space3.setPreferredSize(new java.awt.Dimension(25, 0));
        toolbar.add(space3);

        getContentPane().add(toolbar, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_BookFlight.setBackground(new java.awt.Color(0, 0, 0));
        lbl_BookFlight.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_BookFlight.setForeground(new java.awt.Color(96, 93, 236));
        lbl_BookFlight.setText("Book Flight");
        body.add(lbl_BookFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, -1));

        lbl_FlightName.setBackground(new java.awt.Color(0, 0, 0));
        lbl_FlightName.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbl_FlightName.setForeground(new java.awt.Color(96, 93, 236));
        lbl_FlightName.setText("Flight name:");
        body.add(lbl_FlightName, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        txt_FlightName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_FlightName.setForeground(new java.awt.Color(124, 141, 176));
        body.add(txt_FlightName, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 160, 50));

        lbl_Source.setBackground(new java.awt.Color(0, 0, 0));
        lbl_Source.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbl_Source.setForeground(new java.awt.Color(96, 93, 236));
        lbl_Source.setText("Source:");
        body.add(lbl_Source, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        txt_Source.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Source.setForeground(new java.awt.Color(124, 141, 176));
        body.add(txt_Source, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 160, 50));

        lbl_Destination.setBackground(new java.awt.Color(0, 0, 0));
        lbl_Destination.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbl_Destination.setForeground(new java.awt.Color(96, 93, 236));
        lbl_Destination.setText("Destination:");
        body.add(lbl_Destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        txt_Destination.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Destination.setForeground(new java.awt.Color(124, 141, 176));
        body.add(txt_Destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 150, 50));

        txt_Date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Date.setForeground(new java.awt.Color(124, 141, 176));
        body.add(txt_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 150, 50));

        lbl_Time.setBackground(new java.awt.Color(0, 0, 0));
        lbl_Time.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbl_Time.setForeground(new java.awt.Color(96, 93, 236));
        lbl_Time.setText("Time:");
        body.add(lbl_Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, -1, -1));

        txt_Time.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Time.setForeground(new java.awt.Color(124, 141, 176));
        body.add(txt_Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 150, 50));

        lbl_Date.setBackground(new java.awt.Color(0, 0, 0));
        lbl_Date.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbl_Date.setForeground(new java.awt.Color(96, 93, 236));
        lbl_Date.setText("Date:");
        body.add(lbl_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));

        lbl_BusinessSeat.setBackground(new java.awt.Color(0, 0, 0));
        lbl_BusinessSeat.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbl_BusinessSeat.setForeground(new java.awt.Color(96, 93, 236));
        lbl_BusinessSeat.setText("Business seat:");
        body.add(lbl_BusinessSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 150, -1));

        spn_BusinessSeat.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        spn_BusinessSeat.setBorder(null);
        spn_BusinessSeat.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spn_BusinessSeatStateChanged(evt);
            }
        });
        spn_BusinessSeat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spn_BusinessSeatMouseClicked(evt);
            }
        });
        body.add(spn_BusinessSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, 60, 30));

        lbl_EconomicSeat.setBackground(new java.awt.Color(0, 0, 0));
        lbl_EconomicSeat.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbl_EconomicSeat.setForeground(new java.awt.Color(96, 93, 236));
        lbl_EconomicSeat.setText("Economic seat:");
        body.add(lbl_EconomicSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, 150, -1));

        spn_EconomicSeat.setModel(new javax.swing.SpinnerNumberModel(1, 0, 5, 1));
        spn_EconomicSeat.setBorder(null);
        spn_EconomicSeat.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spn_EconomicSeatStateChanged(evt);
            }
        });
        spn_EconomicSeat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spn_EconomicSeatMouseClicked(evt);
            }
        });
        body.add(spn_EconomicSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 200, 60, 30));

        lbl_BagNumber.setBackground(new java.awt.Color(0, 0, 0));
        lbl_BagNumber.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbl_BagNumber.setForeground(new java.awt.Color(96, 93, 236));
        lbl_BagNumber.setText("Bag number:");
        body.add(lbl_BagNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, 150, -1));

        spn_BagNumber.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        spn_BagNumber.setBorder(null);
        spn_BagNumber.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spn_BagNumberStateChanged(evt);
            }
        });
        spn_BagNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spn_BagNumberMouseClicked(evt);
            }
        });
        body.add(spn_BagNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 250, 60, 30));

        lbl_Price.setBackground(new java.awt.Color(0, 0, 0));
        lbl_Price.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbl_Price.setForeground(new java.awt.Color(96, 93, 236));
        lbl_Price.setText("Price:");
        body.add(lbl_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, 60, -1));

        txt_Price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Price.setForeground(new java.awt.Color(124, 141, 176));
        body.add(txt_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 410, 150, 40));

        btn_BoolFlight.setBackground(new java.awt.Color(96, 93, 236));
        btn_BoolFlight.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_BoolFlight.setForeground(new java.awt.Color(255, 255, 255));
        btn_BoolFlight.setText("Book Flight");
        btn_BoolFlight.setPreferredSize(new java.awt.Dimension(95, 48));
        btn_BoolFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BoolFlightActionPerformed(evt);
            }
        });
        body.add(btn_BoolFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, 140, -1));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlineticketbookingsystem/assets/WorldMap.png"))); // NOI18N
        body.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 700));

        getContentPane().add(body, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FlightsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlightsMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new UserHomePage().setVisible(true);
    }//GEN-LAST:event_FlightsMouseClicked

    private void BookedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookedMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new BookedPage().setVisible(true);
    }//GEN-LAST:event_BookedMouseClicked

    private void AccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new AccountUserPage().setVisible(true);
    }//GEN-LAST:event_AccountMouseClicked

    private void spn_BusinessSeatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spn_BusinessSeatMouseClicked
        // TODO add your handling code here:
        updateprice();
    }//GEN-LAST:event_spn_BusinessSeatMouseClicked

    private void spn_EconomicSeatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spn_EconomicSeatMouseClicked
        // TODO add your handling code here:
        updateprice();
    }//GEN-LAST:event_spn_EconomicSeatMouseClicked

    private void spn_BagNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spn_BagNumberMouseClicked
        // TODO add your handling code here:
        updateprice();
        
    }//GEN-LAST:event_spn_BagNumberMouseClicked

    private void spn_BusinessSeatStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spn_BusinessSeatStateChanged
        // TODO add your handling code here:
        updateprice();
    }//GEN-LAST:event_spn_BusinessSeatStateChanged

    private void spn_EconomicSeatStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spn_EconomicSeatStateChanged
        // TODO add your handling code here:
        updateprice();
    }//GEN-LAST:event_spn_EconomicSeatStateChanged

    private void spn_BagNumberStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spn_BagNumberStateChanged
        // TODO add your handling code here:
        updateprice();
    }//GEN-LAST:event_spn_BagNumberStateChanged

    private void btn_BoolFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BoolFlightActionPerformed
        // TODO add your handling code here:
        pnum = Integer.valueOf(spn_BusinessSeat.getValue().toString());
        eenum = Integer.valueOf(spn_EconomicSeat.getValue().toString());
        bnum = Integer.valueOf(spn_BagNumber.getValue().toString());
        int uid = AppSession.getCurrentUser().getId();
        int fid = cur.getId();
        userDAO.addUserFlight(uid, fid, bnum, eenum, bnum);
        JOptionPane.showMessageDialog(null, "Flight booked Successfully");
        this.dispose();
        new BookedPage().setVisible(true);
    }//GEN-LAST:event_btn_BoolFlightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("default".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Account;
    private javax.swing.JPanel BigSpace;
    private javax.swing.JLabel Booked;
    private javax.swing.JLabel Flights;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel background;
    private javax.swing.JPanel body;
    private javax.swing.JButton btn_BoolFlight;
    private javax.swing.JLabel lbl_BagNumber;
    private javax.swing.JLabel lbl_BookFlight;
    private javax.swing.JLabel lbl_BusinessSeat;
    private javax.swing.JLabel lbl_Date;
    private javax.swing.JLabel lbl_Destination;
    private javax.swing.JLabel lbl_EconomicSeat;
    private javax.swing.JLabel lbl_FlightName;
    private javax.swing.JLabel lbl_Price;
    private javax.swing.JLabel lbl_Source;
    private javax.swing.JLabel lbl_Time;
    private javax.swing.JLabel space1;
    private javax.swing.JLabel space2;
    private javax.swing.JLabel space3;
    private javax.swing.JSpinner spn_BagNumber;
    private javax.swing.JSpinner spn_BusinessSeat;
    private javax.swing.JSpinner spn_EconomicSeat;
    private javax.swing.JPanel toolbar;
    private javax.swing.JLabel txt_Date;
    private javax.swing.JLabel txt_Destination;
    private javax.swing.JLabel txt_FlightName;
    private javax.swing.JLabel txt_Price;
    private javax.swing.JLabel txt_Source;
    private javax.swing.JLabel txt_Time;
    // End of variables declaration//GEN-END:variables
}
