/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airlineticketbookingsystem.Pages;
import airlineticketbookingsystem.dbconnection.*;
import airlineticketbookingsystem.models.*;
import javax.swing.JOptionPane;
/**
 *
 * @author taake
 */
public class LoginPage extends javax.swing.JFrame {

    UserDAO userDAO = new UserDAO();
    String email, password;
    public LoginPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        message_email.setVisible(false);
        message_pass.setVisible(false);
        message_wrong.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        BigSpace = new javax.swing.JPanel();
        Flights = new javax.swing.JLabel();
        space1 = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        space2 = new javax.swing.JLabel();
        SignUp = new javax.swing.JButton();
        space3 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        login_panel = new javax.swing.JPanel();
        Login_txt = new javax.swing.JLabel();
        txt_eml = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        seperator1 = new javax.swing.JSeparator();
        message_email = new javax.swing.JLabel();
        txt_pass = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        seperator2 = new javax.swing.JSeparator();
        btn_login = new javax.swing.JButton();
        message_pass = new javax.swing.JLabel();
        message_wrong = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 796));

        toolbar.setBackground(new java.awt.Color(255, 255, 255));
        toolbar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(124, 141, 176), 1, true));
        toolbar.setAlignmentX(0.0F);
        toolbar.setAlignmentY(0.0F);
        toolbar.setPreferredSize(new java.awt.Dimension(1440, 96));
        toolbar.setLayout(new javax.swing.BoxLayout(toolbar, javax.swing.BoxLayout.X_AXIS));

        Logo.setBackground(new java.awt.Color(153, 153, 0));
        Logo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Logo.setForeground(new java.awt.Color(96, 93, 236));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Logo.setText("Flighty");
        Logo.setToolTipText("");
        Logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Logo.setPreferredSize(new java.awt.Dimension(107, 30));
        toolbar.add(Logo);

        BigSpace.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout BigSpaceLayout = new javax.swing.GroupLayout(BigSpace);
        BigSpace.setLayout(BigSpaceLayout);
        BigSpaceLayout.setHorizontalGroup(
            BigSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1096, Short.MAX_VALUE)
        );
        BigSpaceLayout.setVerticalGroup(
            BigSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        toolbar.add(BigSpace);

        Flights.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Flights.setForeground(new java.awt.Color(124, 141, 176));
        Flights.setText("Flights");
        Flights.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlightsMouseClicked(evt);
            }
        });
        toolbar.add(Flights);

        space1.setPreferredSize(new java.awt.Dimension(15, 0));
        toolbar.add(space1);

        Login.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Login.setForeground(new java.awt.Color(96, 93, 236));
        Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login.setText("Login");
        toolbar.add(Login);

        space2.setPreferredSize(new java.awt.Dimension(15, 0));
        toolbar.add(space2);

        SignUp.setBackground(new java.awt.Color(96, 93, 236));
        SignUp.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        SignUp.setForeground(new java.awt.Color(255, 255, 255));
        SignUp.setText("Sign up");
        SignUp.setMaximumSize(new java.awt.Dimension(95, 48));
        SignUp.setPreferredSize(new java.awt.Dimension(95, 48));
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });
        toolbar.add(SignUp);

        space3.setPreferredSize(new java.awt.Dimension(25, 0));
        toolbar.add(space3);

        getContentPane().add(toolbar, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_panel.setBackground(new java.awt.Color(255, 255, 255));
        login_panel.setPreferredSize(new java.awt.Dimension(548, 513));
        login_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login_txt.setBackground(new java.awt.Color(0, 0, 0));
        Login_txt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Login_txt.setForeground(new java.awt.Color(96, 93, 236));
        Login_txt.setText("Login");
        login_panel.add(Login_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        txt_eml.setBackground(new java.awt.Color(0, 0, 0));
        txt_eml.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txt_eml.setForeground(new java.awt.Color(96, 93, 236));
        txt_eml.setText("Email");
        login_panel.add(txt_eml, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        txt_email.setBackground(new java.awt.Color(255, 255, 255));
        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_email.setForeground(new java.awt.Color(124, 141, 176));
        txt_email.setText("Email");
        txt_email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txt_email.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emailFocusLost(evt);
            }
        });
        login_panel.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 340, 40));

        seperator1.setForeground(new java.awt.Color(124, 141, 176));
        login_panel.add(seperator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 340, 10));

        message_email.setForeground(new java.awt.Color(255, 0, 0));
        login_panel.add(message_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        txt_pass.setBackground(new java.awt.Color(0, 0, 0));
        txt_pass.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(96, 93, 236));
        txt_pass.setText("Password");
        login_panel.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        txt_password.setBackground(new java.awt.Color(255, 255, 255));
        txt_password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_password.setForeground(new java.awt.Color(124, 141, 176));
        txt_password.setText("Password");
        txt_password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txt_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_passwordFocusLost(evt);
            }
        });
        login_panel.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 340, 40));

        seperator2.setForeground(new java.awt.Color(124, 141, 176));
        login_panel.add(seperator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 340, 10));

        btn_login.setBackground(new java.awt.Color(96, 93, 236));
        btn_login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Login");
        btn_login.setPreferredSize(new java.awt.Dimension(95, 48));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        login_panel.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        message_pass.setForeground(new java.awt.Color(255, 0, 0));
        login_panel.add(message_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        message_wrong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        message_wrong.setForeground(new java.awt.Color(255, 0, 0));
        message_wrong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        message_wrong.setText("Wrong Password");
        login_panel.add(message_wrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        body.add(login_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 560, 520));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlineticketbookingsystem/assets/Login.png"))); // NOI18N
        body.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, 460, 400));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlineticketbookingsystem/assets/WorldMap.png"))); // NOI18N
        body.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 700));

        getContentPane().add(body, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean checkEmail() {
        if (email.isEmpty() || email.equals("Email")) {
            message_email.setText("*Enter email");
            message_email.setVisible(true);
            return false;
        }
        if (!email.contains("@gmail.com")) {
            message_email.setText("*Enter valid email");
            message_email.setVisible(true);
            return false;
        }
        if (!userDAO.checkEmailFound(email)) {
            message_email.setText("*Email not found!");
            message_email.setVisible(true);
            return false;
        }
        return true;
    }
    
    private boolean checkPassword() {
        if (password.isEmpty() || password.equals("Password")) {
            message_pass.setText("*Enter Password");
            message_pass.setVisible(true);
            return false;
        }
        return true;
    }
    
    private void txt_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusGained
        // TODO add your handling code here:
        if (txt_email.getText().equals("Email")) {
            txt_email.setText("");
        }
        message_email.setVisible(false);
        message_wrong.setVisible(false);
    }//GEN-LAST:event_txt_emailFocusGained

    private void txt_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusLost
        // TODO add your handling code here:
        if (txt_email.getText().length()==0) {
            txt_email.setText("Email");
        }
    }//GEN-LAST:event_txt_emailFocusLost

    private void txt_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusGained
        // TODO add your handling code here:
        if (txt_password.getText().equals("Password")) {
            txt_password.setText("");
        }
        message_pass.setVisible(false);
        message_wrong.setVisible(false);
    }//GEN-LAST:event_txt_passwordFocusGained

    private void txt_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusLost
        // TODO add your handling code here:
        if (txt_password.getText().length()==0) {
            txt_password.setText("Password");
        }
    }//GEN-LAST:event_txt_passwordFocusLost

    private void FlightsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlightsMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new MainPage().setVisible(true);
    }//GEN-LAST:event_FlightsMouseClicked

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new SignUpPage().setVisible(true);
    }//GEN-LAST:event_SignUpActionPerformed

    
    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:\
        email = txt_email.getText();
        password = txt_password.getText();
        boolean isvalid = true;
        if (!checkEmail()) isvalid = false;
        if (!checkPassword()) isvalid = false;
        if (!isvalid) return;
        if (!userDAO.checkUserLogin(email, password)) {
            message_wrong.setVisible(true);
            return;
        }
        User user = userDAO.getUserByEmail(email);
        AppSession.setCurrentUser(user);
        this.dispose();
        if (user.getRole().equals("user")) new UserHomePage().setVisible(true);
        else new AdminHomePage().setVisible(true);
    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("default".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BigSpace;
    private javax.swing.JLabel Flights;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Login_txt;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton SignUp;
    private javax.swing.JLabel background;
    private javax.swing.JPanel body;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel login_panel;
    private javax.swing.JLabel message_email;
    private javax.swing.JLabel message_pass;
    private javax.swing.JLabel message_wrong;
    private javax.swing.JSeparator seperator1;
    private javax.swing.JSeparator seperator2;
    private javax.swing.JLabel space1;
    private javax.swing.JLabel space2;
    private javax.swing.JLabel space3;
    private javax.swing.JPanel toolbar;
    private javax.swing.JTextField txt_email;
    private javax.swing.JLabel txt_eml;
    private javax.swing.JLabel txt_pass;
    private javax.swing.JTextField txt_password;
    // End of variables declaration//GEN-END:variables
}
