/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airlineticketbookingsystem.Pages;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import airlineticketbookingsystem.dbconnection.*;
import airlineticketbookingsystem.models.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author taake
 */
public class ManageAirportsPage extends javax.swing.JFrame {
    DefaultTableModel dtm;
    Airport airport;
    AirportsDAO airportDAO = new AirportsDAO();
    List<Airport> airports;
    public ManageAirportsPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        message_price.setVisible(false);
        message_airportname.setVisible(false);
        flight_tbl.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        flight_tbl.getTableHeader().setBackground(new Color(184, 183, 240));
        flight_tbl.getTableHeader().setForeground(Color.black);
        flight_tbl.getTableHeader().setPreferredSize(new Dimension(flight_tbl.getColumnModel().getTotalColumnWidth(), 40));
        flight_tbl.setGridColor(Color.black);
        flight_tbl.setBackground(Color.white);
        flight_tbl.getColumnModel().getColumn(0).setPreferredWidth(30);
        flight_tbl.getColumnModel().getColumn(1).setPreferredWidth(100);
        flight_tbl.getColumnModel().getColumn(2).setPreferredWidth(80);
        
        dtm = new DefaultTableModel();
        dtm.addColumn("ID");
        dtm.addColumn("Airport Name");
        dtm.addColumn("Price");
        fillflight_tbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        BigSpace = new javax.swing.JPanel();
        Flights = new javax.swing.JLabel();
        space1 = new javax.swing.JLabel();
        ManageFlights = new javax.swing.JLabel();
        space2 = new javax.swing.JLabel();
        ManageAirports = new javax.swing.JLabel();
        space3 = new javax.swing.JLabel();
        Account = new javax.swing.JButton();
        space4 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        flight_tbl = new javax.swing.JTable();
        lbl_BusinessSeat = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        separtor1 = new javax.swing.JSeparator();
        lbl_EconomicSeat = new javax.swing.JLabel();
        txt_AirportName = new javax.swing.JTextField();
        message_airportname = new javax.swing.JLabel();
        separtor2 = new javax.swing.JSeparator();
        lbl_BagNumber = new javax.swing.JLabel();
        txt_Price = new javax.swing.JTextField();
        message_price = new javax.swing.JLabel();
        separtor3 = new javax.swing.JSeparator();
        btn_Add = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolbar.setBackground(new java.awt.Color(255, 255, 255));
        toolbar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(124, 141, 176), 1, true));
        toolbar.setAlignmentX(0.0F);
        toolbar.setAlignmentY(0.0F);
        toolbar.setPreferredSize(new java.awt.Dimension(1440, 96));
        toolbar.setLayout(new javax.swing.BoxLayout(toolbar, javax.swing.BoxLayout.X_AXIS));

        Logo.setBackground(new java.awt.Color(153, 153, 0));
        Logo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Logo.setForeground(new java.awt.Color(96, 93, 236));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Logo.setText("Flighty");
        Logo.setToolTipText("");
        Logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Logo.setPreferredSize(new java.awt.Dimension(107, 30));
        toolbar.add(Logo);

        BigSpace.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout BigSpaceLayout = new javax.swing.GroupLayout(BigSpace);
        BigSpace.setLayout(BigSpaceLayout);
        BigSpaceLayout.setHorizontalGroup(
            BigSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        BigSpaceLayout.setVerticalGroup(
            BigSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        toolbar.add(BigSpace);

        Flights.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Flights.setForeground(new java.awt.Color(124, 141, 176));
        Flights.setText("Flights");
        Flights.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlightsMouseClicked(evt);
            }
        });
        toolbar.add(Flights);

        space1.setPreferredSize(new java.awt.Dimension(15, 0));
        toolbar.add(space1);

        ManageFlights.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ManageFlights.setForeground(new java.awt.Color(124, 141, 176));
        ManageFlights.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManageFlights.setText("Manage flights");
        ManageFlights.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageFlightsMouseClicked(evt);
            }
        });
        toolbar.add(ManageFlights);

        space2.setPreferredSize(new java.awt.Dimension(15, 0));
        toolbar.add(space2);

        ManageAirports.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ManageAirports.setForeground(new java.awt.Color(96, 93, 236));
        ManageAirports.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManageAirports.setText("Manage airports");
        toolbar.add(ManageAirports);

        space3.setPreferredSize(new java.awt.Dimension(15, 0));
        toolbar.add(space3);

        Account.setBackground(new java.awt.Color(96, 93, 236));
        Account.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Account.setForeground(new java.awt.Color(255, 255, 255));
        Account.setText("Account");
        Account.setMaximumSize(new java.awt.Dimension(95, 48));
        Account.setPreferredSize(new java.awt.Dimension(95, 48));
        Account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountMouseClicked(evt);
            }
        });
        toolbar.add(Account);

        space4.setPreferredSize(new java.awt.Dimension(25, 0));
        toolbar.add(space4);

        getContentPane().add(toolbar, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        flight_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Airport name", "Price "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        flight_tbl.setRowHeight(40);
        flight_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flight_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(flight_tbl);

        body.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, -1, -1));

        lbl_BusinessSeat.setBackground(new java.awt.Color(0, 0, 0));
        lbl_BusinessSeat.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbl_BusinessSeat.setForeground(new java.awt.Color(96, 93, 236));
        lbl_BusinessSeat.setText("ID:");
        body.add(lbl_BusinessSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 150, -1));

        txt_id.setEditable(false);
        txt_id.setBackground(new java.awt.Color(255, 255, 255));
        txt_id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_id.setForeground(new java.awt.Color(124, 141, 176));
        txt_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txt_id.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        body.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 60, 30));

        separtor1.setForeground(new java.awt.Color(124, 141, 176));
        body.add(separtor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 60, 10));

        lbl_EconomicSeat.setBackground(new java.awt.Color(0, 0, 0));
        lbl_EconomicSeat.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbl_EconomicSeat.setForeground(new java.awt.Color(96, 93, 236));
        lbl_EconomicSeat.setText("Airport Name:");
        body.add(lbl_EconomicSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 150, -1));

        txt_AirportName.setBackground(new java.awt.Color(255, 255, 255));
        txt_AirportName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_AirportName.setForeground(new java.awt.Color(124, 141, 176));
        txt_AirportName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txt_AirportName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_AirportName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_AirportNameFocusGained(evt);
            }
        });
        body.add(txt_AirportName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 160, 30));

        message_airportname.setForeground(new java.awt.Color(255, 0, 0));
        body.add(message_airportname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        separtor2.setForeground(new java.awt.Color(124, 141, 176));
        body.add(separtor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 160, 10));

        lbl_BagNumber.setBackground(new java.awt.Color(0, 0, 0));
        lbl_BagNumber.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbl_BagNumber.setForeground(new java.awt.Color(96, 93, 236));
        lbl_BagNumber.setText("Price:");
        body.add(lbl_BagNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 150, -1));

        txt_Price.setBackground(new java.awt.Color(255, 255, 255));
        txt_Price.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Price.setForeground(new java.awt.Color(124, 141, 176));
        txt_Price.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txt_Price.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_Price.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_PriceFocusGained(evt);
            }
        });
        body.add(txt_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 90, 30));

        message_price.setForeground(new java.awt.Color(255, 0, 0));
        body.add(message_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        separtor3.setForeground(new java.awt.Color(124, 141, 176));
        body.add(separtor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 90, 10));

        btn_Add.setBackground(new java.awt.Color(96, 93, 236));
        btn_Add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Add.setForeground(new java.awt.Color(255, 255, 255));
        btn_Add.setText("Add");
        btn_Add.setPreferredSize(new java.awt.Dimension(95, 48));
        btn_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AddMouseClicked(evt);
            }
        });
        body.add(btn_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 110, 40));

        btn_Update.setBackground(new java.awt.Color(96, 93, 236));
        btn_Update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Update.setForeground(new java.awt.Color(255, 255, 255));
        btn_Update.setText("Update");
        btn_Update.setPreferredSize(new java.awt.Dimension(95, 48));
        btn_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_UpdateMouseClicked(evt);
            }
        });
        body.add(btn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 110, 40));

        btn_Delete.setBackground(new java.awt.Color(124, 141, 176));
        btn_Delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_Delete.setText("Delete");
        btn_Delete.setPreferredSize(new java.awt.Dimension(95, 48));
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });
        body.add(btn_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 110, 40));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlineticketbookingsystem/assets/WorldMap.png"))); // NOI18N
        body.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 700));

        getContentPane().add(body, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void fillflight_tbl() {
        airports = airportDAO.getAllAirports();
        dtm.setRowCount(0);
        for (Airport airport : airports) {
            int id = airport.getId();
            String airportname = airport.getAirportName();
            int price = airport.getPrice();
            dtm.addRow(new Object[]{id, airportname, price});
        }
        flight_tbl.setModel(dtm);
    }
    
    private void FlightsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlightsMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new AdminHomePage().setVisible(true);
    }//GEN-LAST:event_FlightsMouseClicked

    private void ManageFlightsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageFlightsMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new ManageFlightsPage().setVisible(true);
    }//GEN-LAST:event_ManageFlightsMouseClicked

    private void AccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new AccountAdminPage().setVisible(true);
    }//GEN-LAST:event_AccountMouseClicked

    private boolean chcckn(String s) {
        if (s.isEmpty()) {
            message_airportname.setText("*Enter airport name");
            message_airportname.setVisible(true);
            return false;
        }
        return true;
    }
    
    private boolean chcckp(String s) {
        if (s.isEmpty()) {
            message_price.setText("*Enter price");
            message_price.setVisible(true);
            return false;
        }
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException e) {
            message_price.setText("*Enter valid price");
            message_price.setVisible(true);
            return false;
        }
    }
    
    private void flight_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flight_tblMouseClicked
        // TODO add your handling code here:
        airport = airports.get(flight_tbl.getSelectedRow());
        txt_id.setText(String.valueOf(airport.getId()));
        txt_AirportName.setText(airport.getAirportName());
        txt_Price.setText(String.valueOf(airport.getPrice()));
    }//GEN-LAST:event_flight_tblMouseClicked

    private void btn_AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AddMouseClicked
        // TODO add your handling code here:
        String airportname = txt_AirportName.getText();
        boolean isvalid = true;
        if (!chcckn(txt_AirportName.getText())) isvalid = false;
        if (!chcckp(txt_Price.getText())) isvalid = false;
        if (!isvalid) return;
        int price = Integer.parseInt(txt_Price.getText());
        Airport ap = new Airport(0, airportname, price);
        airportDAO.addAirport(ap);
        fillflight_tbl();
        JOptionPane.showMessageDialog(null, "Airport Added Successfully");
    }//GEN-LAST:event_btn_AddMouseClicked

    private void btn_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UpdateMouseClicked
        // TODO add your handling code here:
        if (txt_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "You must choose airport first!");
            return;
        }
        airport = airports.get(flight_tbl.getSelectedRow());
        boolean isvalid = true;
        if (!chcckn(txt_AirportName.getText())) isvalid = false;
        if (!chcckp(txt_Price.getText())) isvalid = false;
        if (!isvalid) return;
        int id = Integer.parseInt(txt_id.getText());
        String airportname = txt_AirportName.getText();
        int price = Integer.parseInt(txt_Price.getText());
        if (!(airport.getAirportName().equals(airportname) && airport.getPrice() == price)) {
            Airport ap = new Airport(id, airportname, price);
            airportDAO.updateAirport(ap);
            fillflight_tbl();
            JOptionPane.showMessageDialog(null, "Airport Updated Successfully");
        } else JOptionPane.showMessageDialog(null, "You made no changes!");
    }//GEN-LAST:event_btn_UpdateMouseClicked

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        // TODO add your handling code here:
        airport = airports.get(flight_tbl.getSelectedRow());
        int id = airport.getId();
        airportDAO.deleteAirport(id);
        fillflight_tbl();
        JOptionPane.showMessageDialog(null, "Airport Deleted Successfully");
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void txt_PriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PriceFocusGained
        // TODO add your handling code here:
        message_price.setVisible(false);
    }//GEN-LAST:event_txt_PriceFocusGained

    private void txt_AirportNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_AirportNameFocusGained
        // TODO add your handling code here:
        message_airportname.setVisible(false);
    }//GEN-LAST:event_txt_AirportNameFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("default".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageAirportsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageAirportsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageAirportsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageAirportsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageAirportsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Account;
    private javax.swing.JPanel BigSpace;
    private javax.swing.JLabel Flights;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel ManageAirports;
    private javax.swing.JLabel ManageFlights;
    private javax.swing.JLabel background;
    private javax.swing.JPanel body;
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Update;
    private javax.swing.JTable flight_tbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_BagNumber;
    private javax.swing.JLabel lbl_BusinessSeat;
    private javax.swing.JLabel lbl_EconomicSeat;
    private javax.swing.JLabel message_airportname;
    private javax.swing.JLabel message_price;
    private javax.swing.JSeparator separtor1;
    private javax.swing.JSeparator separtor2;
    private javax.swing.JSeparator separtor3;
    private javax.swing.JLabel space1;
    private javax.swing.JLabel space2;
    private javax.swing.JLabel space3;
    private javax.swing.JLabel space4;
    private javax.swing.JPanel toolbar;
    private javax.swing.JTextField txt_AirportName;
    private javax.swing.JTextField txt_Price;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
