/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airlineticketbookingsystem.Pages;

import airlineticketbookingsystem.dbconnection.AirportsDAO;
import airlineticketbookingsystem.dbconnection.FlightsDAO;
import airlineticketbookingsystem.models.Airport;
import airlineticketbookingsystem.models.Flight;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author taake
 */
public class ManageFlightsPage extends javax.swing.JFrame {
    Flight flight = new Flight();
    AirportsDAO airportDAO = new AirportsDAO();
    List<Airport> airports = airportDAO.getAllAirports();
    FlightsDAO flightDAO = new FlightsDAO();
    String flightname, datee, destination, source, timee, ffdes, ffsrc;
    int economicseat, bagnumber, businessseat;
    public ManageFlightsPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        txt_Date.setText("");
        for (Airport airport : airports) {
            cmb_Destination.addItem(airport.getAirportName());
            cmb_Source.addItem(airport.getAirportName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        date = new com.raven.datechooser.DateChooser();
        toolbar = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        BigSpace = new javax.swing.JPanel();
        Flights = new javax.swing.JLabel();
        space1 = new javax.swing.JLabel();
        ManageFlights = new javax.swing.JLabel();
        space2 = new javax.swing.JLabel();
        ManageAirports = new javax.swing.JLabel();
        space3 = new javax.swing.JLabel();
        Account = new javax.swing.JButton();
        space4 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        txt_id = new javax.swing.JTextField();
        separtor4 = new javax.swing.JSeparator();
        btn_Serach = new javax.swing.JButton();
        lbl_BusinessSeat1 = new javax.swing.JLabel();
        lbl_BookFlight = new javax.swing.JLabel();
        lbl_FlightName = new javax.swing.JLabel();
        spn_BusinessSeat = new javax.swing.JSpinner();
        spn_EconomicSeat = new javax.swing.JSpinner();
        spn_BagNumber = new javax.swing.JSpinner();
        txt_FlightName = new javax.swing.JTextField();
        lbl_Source = new javax.swing.JLabel();
        cmb_Source = new javax.swing.JComboBox<>();
        cmb_Destination = new javax.swing.JComboBox<>();
        separtor6 = new javax.swing.JSeparator();
        lbl_Destination = new javax.swing.JLabel();
        lbl_Date = new javax.swing.JLabel();
        txt_Date = new javax.swing.JTextField();
        separtor8 = new javax.swing.JSeparator();
        lbl_Time = new javax.swing.JLabel();
        txt_Time = new javax.swing.JTextField();
        separtor10 = new javax.swing.JSeparator();
        separtor9 = new javax.swing.JSeparator();
        lbl_BusinessSeat = new javax.swing.JLabel();
        lbl_EconomicSeat = new javax.swing.JLabel();
        lbl_BagNumber = new javax.swing.JLabel();
        lbl_Price = new javax.swing.JLabel();
        txt_Price = new javax.swing.JTextField();
        btn_Add = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        message_id = new javax.swing.JLabel();
        message_flightname = new javax.swing.JLabel();
        message_source = new javax.swing.JLabel();
        message_destination = new javax.swing.JLabel();
        message_date = new javax.swing.JLabel();
        message_timer = new javax.swing.JLabel();
        message_businessseat = new javax.swing.JLabel();
        message_economicseat = new javax.swing.JLabel();
        message_bagnumber = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        date.setForeground(new java.awt.Color(96, 93, 236));
        date.setTextRefernce(txt_Date);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolbar.setBackground(new java.awt.Color(255, 255, 255));
        toolbar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(124, 141, 176), 1, true));
        toolbar.setAlignmentX(0.0F);
        toolbar.setAlignmentY(0.0F);
        toolbar.setPreferredSize(new java.awt.Dimension(1440, 96));
        toolbar.setLayout(new javax.swing.BoxLayout(toolbar, javax.swing.BoxLayout.X_AXIS));

        Logo.setBackground(new java.awt.Color(153, 153, 0));
        Logo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Logo.setForeground(new java.awt.Color(96, 93, 236));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Logo.setText("Flighty");
        Logo.setToolTipText("");
        Logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Logo.setPreferredSize(new java.awt.Dimension(107, 30));
        toolbar.add(Logo);

        BigSpace.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout BigSpaceLayout = new javax.swing.GroupLayout(BigSpace);
        BigSpace.setLayout(BigSpaceLayout);
        BigSpaceLayout.setHorizontalGroup(
            BigSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        BigSpaceLayout.setVerticalGroup(
            BigSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        toolbar.add(BigSpace);

        Flights.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Flights.setForeground(new java.awt.Color(124, 141, 176));
        Flights.setText("Flights");
        Flights.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlightsMouseClicked(evt);
            }
        });
        toolbar.add(Flights);

        space1.setPreferredSize(new java.awt.Dimension(15, 0));
        toolbar.add(space1);

        ManageFlights.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ManageFlights.setForeground(new java.awt.Color(96, 93, 236));
        ManageFlights.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManageFlights.setText("Manage flights");
        toolbar.add(ManageFlights);

        space2.setPreferredSize(new java.awt.Dimension(15, 0));
        toolbar.add(space2);

        ManageAirports.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ManageAirports.setForeground(new java.awt.Color(124, 141, 176));
        ManageAirports.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManageAirports.setText("Manage airports");
        ManageAirports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageAirportsMouseClicked(evt);
            }
        });
        toolbar.add(ManageAirports);

        space3.setPreferredSize(new java.awt.Dimension(15, 0));
        toolbar.add(space3);

        Account.setBackground(new java.awt.Color(96, 93, 236));
        Account.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Account.setForeground(new java.awt.Color(255, 255, 255));
        Account.setText("Account");
        Account.setMaximumSize(new java.awt.Dimension(95, 48));
        Account.setPreferredSize(new java.awt.Dimension(95, 48));
        Account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountMouseClicked(evt);
            }
        });
        toolbar.add(Account);

        space4.setPreferredSize(new java.awt.Dimension(25, 0));
        toolbar.add(space4);

        getContentPane().add(toolbar, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_id.setBackground(new java.awt.Color(255, 255, 255));
        txt_id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_id.setForeground(new java.awt.Color(124, 141, 176));
        txt_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txt_id.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_idFocusGained(evt);
            }
        });
        body.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 60, 30));

        separtor4.setForeground(new java.awt.Color(124, 141, 176));
        body.add(separtor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 190, 10));

        btn_Serach.setBackground(new java.awt.Color(96, 93, 236));
        btn_Serach.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Serach.setForeground(new java.awt.Color(255, 255, 255));
        btn_Serach.setText("Serach");
        btn_Serach.setPreferredSize(new java.awt.Dimension(95, 48));
        btn_Serach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SerachActionPerformed(evt);
            }
        });
        body.add(btn_Serach, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, 30));

        lbl_BusinessSeat1.setBackground(new java.awt.Color(0, 0, 0));
        lbl_BusinessSeat1.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbl_BusinessSeat1.setForeground(new java.awt.Color(96, 93, 236));
        lbl_BusinessSeat1.setText("ID:");
        body.add(lbl_BusinessSeat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 40, -1));

        lbl_BookFlight.setBackground(new java.awt.Color(0, 0, 0));
        lbl_BookFlight.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_BookFlight.setForeground(new java.awt.Color(96, 93, 236));
        lbl_BookFlight.setText("Manage Flight");
        body.add(lbl_BookFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, -1, -1));

        lbl_FlightName.setBackground(new java.awt.Color(0, 0, 0));
        lbl_FlightName.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbl_FlightName.setForeground(new java.awt.Color(96, 93, 236));
        lbl_FlightName.setText("Flight name:");
        body.add(lbl_FlightName, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        spn_BusinessSeat.setModel(new javax.swing.SpinnerNumberModel(1, 0, 200, 1));
        spn_BusinessSeat.setBorder(null);
        spn_BusinessSeat.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spn_BusinessSeatStateChanged(evt);
            }
        });
        spn_BusinessSeat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spn_BusinessSeatMouseClicked(evt);
            }
        });
        body.add(spn_BusinessSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 160, 60, 30));

        spn_EconomicSeat.setModel(new javax.swing.SpinnerNumberModel(0, 0, 200, 1));
        spn_EconomicSeat.setBorder(null);
        spn_EconomicSeat.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spn_EconomicSeatStateChanged(evt);
            }
        });
        spn_EconomicSeat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                spn_EconomicSeatFocusGained(evt);
            }
        });
        spn_EconomicSeat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spn_EconomicSeatMouseClicked(evt);
            }
        });
        body.add(spn_EconomicSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 210, 60, 30));

        spn_BagNumber.setModel(new javax.swing.SpinnerNumberModel(0, 0, 200, 1));
        spn_BagNumber.setBorder(null);
        spn_BagNumber.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spn_BagNumberStateChanged(evt);
            }
        });
        spn_BagNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spn_BagNumberMouseClicked(evt);
            }
        });
        body.add(spn_BagNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 260, 60, 30));

        txt_FlightName.setBackground(new java.awt.Color(255, 255, 255));
        txt_FlightName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_FlightName.setForeground(new java.awt.Color(124, 141, 176));
        txt_FlightName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txt_FlightName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_FlightName.setMinimumSize(new java.awt.Dimension(122, 29));
        txt_FlightName.setPreferredSize(new java.awt.Dimension(122, 29));
        txt_FlightName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_FlightNameFocusGained(evt);
            }
        });
        body.add(txt_FlightName, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 190, 30));

        lbl_Source.setBackground(new java.awt.Color(0, 0, 0));
        lbl_Source.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbl_Source.setForeground(new java.awt.Color(96, 93, 236));
        lbl_Source.setText("Source:");
        body.add(lbl_Source, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        cmb_Source.setBackground(new java.awt.Color(255, 255, 255));
        cmb_Source.setForeground(new java.awt.Color(124, 141, 176));
        cmb_Source.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "From Where ?" }));
        cmb_Source.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(124, 141, 176), 1, true));
        body.add(cmb_Source, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 190, 30));

        cmb_Destination.setBackground(new java.awt.Color(255, 255, 255));
        cmb_Destination.setForeground(new java.awt.Color(124, 141, 176));
        cmb_Destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "From Where ?" }));
        cmb_Destination.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(124, 141, 176), 1, true));
        body.add(cmb_Destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 190, 30));

        separtor6.setForeground(new java.awt.Color(124, 141, 176));
        body.add(separtor6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 190, 10));

        lbl_Destination.setBackground(new java.awt.Color(0, 0, 0));
        lbl_Destination.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbl_Destination.setForeground(new java.awt.Color(96, 93, 236));
        lbl_Destination.setText("Destination:");
        body.add(lbl_Destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));

        lbl_Date.setBackground(new java.awt.Color(0, 0, 0));
        lbl_Date.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbl_Date.setForeground(new java.awt.Color(96, 93, 236));
        lbl_Date.setText("Date:");
        body.add(lbl_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        txt_Date.setBackground(new java.awt.Color(255, 255, 255));
        txt_Date.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Date.setForeground(new java.awt.Color(124, 141, 176));
        txt_Date.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txt_Date.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_Date.setMinimumSize(new java.awt.Dimension(122, 29));
        txt_Date.setPreferredSize(new java.awt.Dimension(122, 29));
        txt_Date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_DateFocusGained(evt);
            }
        });
        body.add(txt_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 190, 30));

        separtor8.setForeground(new java.awt.Color(124, 141, 176));
        body.add(separtor8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 190, 10));

        lbl_Time.setBackground(new java.awt.Color(0, 0, 0));
        lbl_Time.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbl_Time.setForeground(new java.awt.Color(96, 93, 236));
        lbl_Time.setText("Time:");
        body.add(lbl_Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, -1));

        txt_Time.setBackground(new java.awt.Color(255, 255, 255));
        txt_Time.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Time.setForeground(new java.awt.Color(124, 141, 176));
        txt_Time.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txt_Time.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_Time.setMinimumSize(new java.awt.Dimension(122, 29));
        txt_Time.setPreferredSize(new java.awt.Dimension(122, 29));
        txt_Time.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_TimeFocusGained(evt);
            }
        });
        body.add(txt_Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 190, 30));

        separtor10.setForeground(new java.awt.Color(124, 141, 176));
        body.add(separtor10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 190, 10));

        separtor9.setForeground(new java.awt.Color(124, 141, 176));
        body.add(separtor9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 60, 10));

        lbl_BusinessSeat.setBackground(new java.awt.Color(0, 0, 0));
        lbl_BusinessSeat.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbl_BusinessSeat.setForeground(new java.awt.Color(96, 93, 236));
        lbl_BusinessSeat.setText("Business seat:");
        body.add(lbl_BusinessSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 150, -1));

        lbl_EconomicSeat.setBackground(new java.awt.Color(0, 0, 0));
        lbl_EconomicSeat.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbl_EconomicSeat.setForeground(new java.awt.Color(96, 93, 236));
        lbl_EconomicSeat.setText("Economic seat:");
        body.add(lbl_EconomicSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, 150, -1));

        lbl_BagNumber.setBackground(new java.awt.Color(0, 0, 0));
        lbl_BagNumber.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbl_BagNumber.setForeground(new java.awt.Color(96, 93, 236));
        lbl_BagNumber.setText("Bag number:");
        body.add(lbl_BagNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, 150, -1));

        lbl_Price.setBackground(new java.awt.Color(0, 0, 0));
        lbl_Price.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbl_Price.setForeground(new java.awt.Color(96, 93, 236));
        lbl_Price.setText("Price:");
        body.add(lbl_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, 60, -1));

        txt_Price.setBackground(new java.awt.Color(255, 255, 255));
        txt_Price.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Price.setForeground(new java.awt.Color(124, 141, 176));
        txt_Price.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txt_Price.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        body.add(txt_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 420, 160, 30));

        btn_Add.setBackground(new java.awt.Color(96, 93, 236));
        btn_Add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Add.setForeground(new java.awt.Color(255, 255, 255));
        btn_Add.setText("Add");
        btn_Add.setPreferredSize(new java.awt.Dimension(95, 48));
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });
        body.add(btn_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, 140, -1));

        btn_Update.setBackground(new java.awt.Color(96, 93, 236));
        btn_Update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Update.setForeground(new java.awt.Color(255, 255, 255));
        btn_Update.setText("Update");
        btn_Update.setPreferredSize(new java.awt.Dimension(95, 48));
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });
        body.add(btn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, 140, -1));

        message_id.setForeground(new java.awt.Color(255, 0, 0));
        body.add(message_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, -1));

        message_flightname.setForeground(new java.awt.Color(255, 0, 0));
        body.add(message_flightname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        message_source.setForeground(new java.awt.Color(255, 0, 0));
        body.add(message_source, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));

        message_destination.setForeground(new java.awt.Color(255, 0, 0));
        body.add(message_destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, -1));

        message_date.setForeground(new java.awt.Color(255, 0, 0));
        body.add(message_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, -1, -1));

        message_timer.setForeground(new java.awt.Color(255, 0, 0));
        body.add(message_timer, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, -1, -1));

        message_businessseat.setForeground(new java.awt.Color(255, 0, 0));
        body.add(message_businessseat, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, -1, -1));

        message_economicseat.setForeground(new java.awt.Color(255, 0, 0));
        body.add(message_economicseat, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, -1, -1));

        message_bagnumber.setForeground(new java.awt.Color(255, 0, 0));
        body.add(message_bagnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 290, -1, -1));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlineticketbookingsystem/assets/WorldMap.png"))); // NOI18N
        body.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 700));

        getContentPane().add(body, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FlightsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlightsMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new AdminHomePage().setVisible(true);
        message_bagnumber.setVisible(false);
        message_businessseat.setVisible(false);
        message_date.setVisible(false);
        message_destination.setVisible(false);
        message_economicseat.setVisible(false);
        message_flightname.setVisible(false);
        message_id.setVisible(false);
        message_source.setVisible(false);
        message_timer.setVisible(false);
    }//GEN-LAST:event_FlightsMouseClicked

    private void ManageAirportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageAirportsMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new ManageAirportsPage().setVisible(true);
    }//GEN-LAST:event_ManageAirportsMouseClicked

    private void AccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new AccountAdminPage().setVisible(true);
    }//GEN-LAST:event_AccountMouseClicked

    private void spn_BusinessSeatStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spn_BusinessSeatStateChanged
        // TODO add your handling code here:
        updateprice();
    }//GEN-LAST:event_spn_BusinessSeatStateChanged

    private void spn_BusinessSeatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spn_BusinessSeatMouseClicked
        // TODO add your handling code here:
        updateprice();
    }//GEN-LAST:event_spn_BusinessSeatMouseClicked

    private void spn_EconomicSeatStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spn_EconomicSeatStateChanged
        // TODO add your handling code here:
        updateprice();
        message_economicseat.setVisible(false);
        
    }//GEN-LAST:event_spn_EconomicSeatStateChanged

    private void spn_EconomicSeatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spn_EconomicSeatMouseClicked
        // TODO add your handling code here:
        message_economicseat.setVisible(false);
        updateprice();
    }//GEN-LAST:event_spn_EconomicSeatMouseClicked

    private void spn_BagNumberStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spn_BagNumberStateChanged
        // TODO add your handling code here:
        updateprice();
    }//GEN-LAST:event_spn_BagNumberStateChanged

    private void spn_BagNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spn_BagNumberMouseClicked
        // TODO add your handling code here:
        updateprice();
    }//GEN-LAST:event_spn_BagNumberMouseClicked

   
    private void btn_SerachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SerachActionPerformed
        // TODO add your handling code here:
        if (!checkid()) return;
        flight = flightDAO.searchFlightsID(Integer.parseInt(txt_id.getText()));
        if (flight == null) {
            JOptionPane.showMessageDialog(null, "Flight ID not found");
            return;
        }
        txt_FlightName.setText(flight.getFlightName());
        ffsrc = flight.getSource();
        ffdes = flight.getDestination();
        cmb_Destination.setSelectedItem(ffdes);
        cmb_Source.setSelectedItem(ffsrc);
        //txt_Source.setText(flight.getSource());
        //txt_Destination.setText(flight.getDestination());
        txt_Date.setText(flight.getDate());
        txt_Time.setText(flight.getTime());
        spn_BusinessSeat.setValue(flight.getBusinessSeat());
        spn_EconomicSeat.setValue(flight.getEconomySeat());
        spn_BagNumber.setValue(flight.getBagNumber());
        spn_BusinessSeat.setEnabled(true);
        updateprice();
    }//GEN-LAST:event_btn_SerachActionPerformed

    private void updateprice() {
        String ssource = cmb_Source.getSelectedItem().toString();
        String ddestination = cmb_Destination.getSelectedItem().toString();
        //source = txt_Source.getText();
        //destination = txt_Destination.getText();
        int sprice = airportDAO.getAirportPrice(ssource);
        int dprice = airportDAO.getAirportPrice(ddestination);
        int total = dprice + sprice; 
        txt_Price.setText(String.valueOf(total));
    }
    
    private void txt_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_idFocusGained
        // TODO add your handling code here:
        message_id.setVisible(false);
    }//GEN-LAST:event_txt_idFocusGained

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        // TODO add your handling code here:
        flightname = txt_FlightName.getText();
        source = cmb_Source.getSelectedItem().toString();
        destination = cmb_Destination.getSelectedItem().toString();
        //source = txt_Source.getText();
        //destination = txt_Destination.getText();
        datee = txt_Date.getText();
        timee = txt_Time.getText();
        businessseat = Integer.parseInt(spn_BusinessSeat.getValue().toString());
        economicseat = Integer.parseInt(spn_EconomicSeat.getValue().toString());
        bagnumber = Integer.parseInt(spn_BagNumber.getValue().toString());
        spn_BusinessSeat.setValue(spn_BusinessSeat.getValue());
        spn_EconomicSeat.setValue(spn_EconomicSeat.getValue());
        spn_BagNumber.setValue(spn_BagNumber.getValue());
        boolean isvalid = true;
        if (!checkFlightName()) isvalid = false; if(!checkSource()) isvalid = false;
        if(!checkDestination()) isvalid = false; if(!checkDate()) isvalid = false; if(!checkTime()) isvalid = false; if(!checkEconomicSeat()) isvalid = false;
        if (!isvalid) return;
//        flight = new Flight()l
        flight.setFlightName(flightname);
        flight.setSource(source);
        flight.setDestination(destination);
        flight.setDate(datee);
        flight.setTime(timee);
        flight.setBusinessSeat(businessseat);
        flight.setEconomySeat(economicseat);
        flight.setBagNumber(bagnumber);
        flightDAO.addFlight(flight);
        JOptionPane.showMessageDialog(null, "Flight Added Successfully");
    }//GEN-LAST:event_btn_AddActionPerformed

    private boolean checkid() {
        if (txt_id.getText().isEmpty()) {
            message_id.setText("*Enter id");
            message_id.setVisible(true);
            return false;
        }
        if (!txt_id.getText().matches("\\d{1,3}")) {
            message_id.setText("*Enter a valid id");
            message_id.setVisible(true);
            return false;
        }
        return true;
    }
    
   private boolean checkFlightName() {
        if (flightname.isEmpty()) {
            message_flightname.setText("*Enter flight name");
            message_flightname.setVisible(true);
            return false;
        }
        if (flightname.length() < 2) {
            message_flightname.setText("*First name is too short");
            message_flightname.setVisible(true);
            return false;
        }
        return true;
    }
   
   private boolean checkSource() {
        if (source.isEmpty()) {
            message_source.setText("*Choose source");
            message_source.setVisible(true);
            return false;
        }
        return true;
    }
   
   private boolean checkDestination() {
        if (destination.isEmpty()) {
            message_destination.setText("*Choose destination");
            message_destination.setVisible(true);
            return false;
        }
        return true;
    }
   
   private boolean checkDate() {
        if (datee.isEmpty()) {
            message_date.setText("*Choose date");
            message_date.setVisible(true);
            return false;
        }
        return true;
    }
   
   private boolean checkTime() {
        if (timee.isEmpty()) {
            message_timer.setText("*Enter time in hours");
            message_timer.setVisible(true);
            return false;
        }
        int timeee = Integer.parseInt(timee);
        if (timeee <= 0 || timeee > 24) {
            message_timer.setText("*Enter a valid time");
            message_timer.setVisible(true);
            return false;
        }
        return true;
    }
   
   private boolean checkEconomicSeat() {
        if (economicseat > 200 || economicseat < 50) {
            message_economicseat.setText("*Enter a valid number");
            message_economicseat.setVisible(true);
            return false;
        }
        return true;
    }
   
   private boolean checkchanges() {
        return !(flightname.equals(flight.getFlightName()) &&
                source.equals(flight.getSource()) &&
                destination.equals(flight.getDestination()) &&
                datee.equals(flight.getDate()) &&
                timee.equals(flight.getTime()) &&
                businessseat == flight.getBusinessSeat() &&
                economicseat == flight.getEconomySeat() &&
                bagnumber == flight.getBagNumber());
    }
   
    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // TODO add your handling code here:
        flightname = txt_FlightName.getText();
        source = cmb_Source.getSelectedItem().toString();
        destination = cmb_Destination.getSelectedItem().toString();
        //source = txt_Source.getText();
        //destination = txt_Destination.getText();
        datee = txt_Date.getText();
        timee = txt_Time.getText();
        businessseat = Integer.parseInt(spn_BusinessSeat.getValue().toString());
        economicseat = Integer.parseInt(spn_EconomicSeat.getValue().toString());
        bagnumber = Integer.parseInt(spn_BagNumber.getValue().toString());
        spn_BusinessSeat.setValue(flight.getBusinessSeat());
        spn_EconomicSeat.setValue(flight.getEconomySeat());
        spn_BagNumber.setValue(flight.getBagNumber());
        spn_BusinessSeat.setEnabled(true);
        boolean isvalid = true;
        if (!checkid()) isvalid = false; if (!checkFlightName()) isvalid = false; if(!checkSource()) isvalid = false;
        if(!checkDestination()) isvalid = false; if(!checkDate()) isvalid = false; if(!checkTime()) isvalid = false; if(!checkEconomicSeat()) isvalid = false;
        if (!checkchanges()) {
            isvalid = false;
            JOptionPane.showMessageDialog(null, "You made no changes");
        }
        if (!isvalid) return;
        flight.setFlightName(flightname);
        flight.setSource(source);
        flight.setDestination(destination);
        flight.setDate(datee);
        flight.setTime(timee);
        flight.setBusinessSeat(businessseat);
        flight.setEconomySeat(economicseat);
        flight.setBagNumber(bagnumber);
        flightDAO.updateFlight(flight);
        JOptionPane.showMessageDialog(null, "Flight Updated Successfully");
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void txt_FlightNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_FlightNameFocusGained
        // TODO add your handling code here:
        message_flightname.setVisible(false);
    }//GEN-LAST:event_txt_FlightNameFocusGained

    private void txt_DateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DateFocusGained
        // TODO add your handling code here:
        message_date.setVisible(false);
    }//GEN-LAST:event_txt_DateFocusGained

    private void txt_TimeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_TimeFocusGained
        // TODO add your handling code here:
        message_timer.setVisible(false);
    }//GEN-LAST:event_txt_TimeFocusGained

    private void spn_EconomicSeatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spn_EconomicSeatFocusGained
        // TODO add your handling code here:
        message_economicseat.setVisible(false);
    }//GEN-LAST:event_spn_EconomicSeatFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("default".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageFlightsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageFlightsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageFlightsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageFlightsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageFlightsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Account;
    private javax.swing.JPanel BigSpace;
    private javax.swing.JLabel Flights;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel ManageAirports;
    private javax.swing.JLabel ManageFlights;
    private javax.swing.JLabel background;
    private javax.swing.JPanel body;
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Serach;
    private javax.swing.JButton btn_Update;
    private javax.swing.JComboBox<String> cmb_Destination;
    private javax.swing.JComboBox<String> cmb_Source;
    private com.raven.datechooser.DateChooser date;
    private javax.swing.JLabel lbl_BagNumber;
    private javax.swing.JLabel lbl_BookFlight;
    private javax.swing.JLabel lbl_BusinessSeat;
    private javax.swing.JLabel lbl_BusinessSeat1;
    private javax.swing.JLabel lbl_Date;
    private javax.swing.JLabel lbl_Destination;
    private javax.swing.JLabel lbl_EconomicSeat;
    private javax.swing.JLabel lbl_FlightName;
    private javax.swing.JLabel lbl_Price;
    private javax.swing.JLabel lbl_Source;
    private javax.swing.JLabel lbl_Time;
    private javax.swing.JLabel message_bagnumber;
    private javax.swing.JLabel message_businessseat;
    private javax.swing.JLabel message_date;
    private javax.swing.JLabel message_destination;
    private javax.swing.JLabel message_economicseat;
    private javax.swing.JLabel message_flightname;
    private javax.swing.JLabel message_id;
    private javax.swing.JLabel message_source;
    private javax.swing.JLabel message_timer;
    private javax.swing.JSeparator separtor10;
    private javax.swing.JSeparator separtor4;
    private javax.swing.JSeparator separtor6;
    private javax.swing.JSeparator separtor8;
    private javax.swing.JSeparator separtor9;
    private javax.swing.JLabel space1;
    private javax.swing.JLabel space2;
    private javax.swing.JLabel space3;
    private javax.swing.JLabel space4;
    private javax.swing.JSpinner spn_BagNumber;
    private javax.swing.JSpinner spn_BusinessSeat;
    private javax.swing.JSpinner spn_EconomicSeat;
    private javax.swing.JPanel toolbar;
    private javax.swing.JTextField txt_Date;
    private javax.swing.JTextField txt_FlightName;
    private javax.swing.JTextField txt_Price;
    private javax.swing.JTextField txt_Time;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
