/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airlineticketbookingsystem.Pages;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import airlineticketbookingsystem.dbconnection.*;
import airlineticketbookingsystem.models.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author taake
 */
public class UserHomePage extends javax.swing.JFrame {
    DefaultTableModel dtm;
    AirportsDAO airportDAO = new AirportsDAO();
    List<Airport> airports = airportDAO.getAllAirports();
    FlightsDAO flightDAO = new FlightsDAO();
    List<Flight> flights;
    public UserHomePage() {
        initComponents();
        this.setLocationRelativeTo(null);
        table_panel.setVisible(false);
        book_btn.setVisible(false);
        txt_date.setText("");
        flight_tbl.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        flight_tbl.getTableHeader().setBackground(new Color(184, 183, 240));
        flight_tbl.getTableHeader().setForeground(Color.black);
        flight_tbl.getTableHeader().setPreferredSize(new Dimension(flight_tbl.getColumnModel().getTotalColumnWidth(), 40));
        flight_tbl.setGridColor(Color.black);
        flight_tbl.setBackground(Color.white);
        for (Airport airport : airports) {
            from_where.addItem(airport.getAirportName());
            to_where.addItem(airport.getAirportName());
        }
        dtm = new DefaultTableModel();
        dtm.addColumn("Flight name");
        dtm.addColumn("Source");
        dtm.addColumn("Destination");
        dtm.addColumn("Date");
        dtm.addColumn("Time");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        date = new com.raven.datechooser.DateChooser();
        toolbar = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        BigSpace = new javax.swing.JPanel();
        Flights = new javax.swing.JLabel();
        space1 = new javax.swing.JLabel();
        Booked = new javax.swing.JLabel();
        space2 = new javax.swing.JLabel();
        Account = new javax.swing.JButton();
        space3 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        allflight_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        from_where = new javax.swing.JComboBox<>();
        to_where = new javax.swing.JComboBox<>();
        date_panel = new javax.swing.JPanel();
        date_label = new javax.swing.JLabel();
        txt_date = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        table_panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        flight_tbl = new javax.swing.JTable();
        book_btn = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        date.setForeground(new java.awt.Color(96, 93, 236));
        date.setTextRefernce(txt_date);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolbar.setBackground(new java.awt.Color(255, 255, 255));
        toolbar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(124, 141, 176), 1, true));
        toolbar.setForeground(new java.awt.Color(124, 141, 176));
        toolbar.setAlignmentX(0.0F);
        toolbar.setAlignmentY(0.0F);
        toolbar.setPreferredSize(new java.awt.Dimension(1440, 96));
        toolbar.setLayout(new javax.swing.BoxLayout(toolbar, javax.swing.BoxLayout.X_AXIS));

        Logo.setBackground(new java.awt.Color(153, 153, 0));
        Logo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Logo.setForeground(new java.awt.Color(96, 93, 236));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Logo.setText("Flighty");
        Logo.setToolTipText("");
        Logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Logo.setPreferredSize(new java.awt.Dimension(107, 30));
        toolbar.add(Logo);

        BigSpace.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout BigSpaceLayout = new javax.swing.GroupLayout(BigSpace);
        BigSpace.setLayout(BigSpaceLayout);
        BigSpaceLayout.setHorizontalGroup(
            BigSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1083, Short.MAX_VALUE)
        );
        BigSpaceLayout.setVerticalGroup(
            BigSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        toolbar.add(BigSpace);

        Flights.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Flights.setForeground(new java.awt.Color(96, 93, 236));
        Flights.setText("Flights");
        toolbar.add(Flights);

        space1.setPreferredSize(new java.awt.Dimension(15, 0));
        toolbar.add(space1);

        Booked.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Booked.setForeground(new java.awt.Color(124, 141, 176));
        Booked.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Booked.setText("Booked");
        Booked.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookedMouseClicked(evt);
            }
        });
        toolbar.add(Booked);

        space2.setPreferredSize(new java.awt.Dimension(15, 0));
        toolbar.add(space2);

        Account.setBackground(new java.awt.Color(96, 93, 236));
        Account.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Account.setForeground(new java.awt.Color(255, 255, 255));
        Account.setText("Account");
        Account.setMaximumSize(new java.awt.Dimension(95, 48));
        Account.setPreferredSize(new java.awt.Dimension(95, 48));
        Account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountMouseClicked(evt);
            }
        });
        toolbar.add(Account);

        space3.setPreferredSize(new java.awt.Dimension(25, 0));
        toolbar.add(space3);

        getContentPane().add(toolbar, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        allflight_btn.setBackground(new java.awt.Color(96, 93, 236));
        allflight_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        allflight_btn.setForeground(new java.awt.Color(255, 255, 255));
        allflight_btn.setText("All Flights");
        allflight_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allflight_btnActionPerformed(evt);
            }
        });
        body.add(allflight_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 100, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(124, 141, 176));
        jLabel1.setText("-------------------------------or-------------------------------");
        body.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        from_where.setBackground(new java.awt.Color(255, 255, 255));
        from_where.setForeground(new java.awt.Color(124, 141, 176));
        from_where.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "From Where ?" }));
        from_where.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(124, 141, 176), 1, true));
        body.add(from_where, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 155, 271, 49));

        to_where.setBackground(new java.awt.Color(255, 255, 255));
        to_where.setForeground(new java.awt.Color(124, 141, 176));
        to_where.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "To Where ?" }));
        to_where.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(124, 141, 176), 1, true));
        to_where.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                to_whereActionPerformed(evt);
            }
        });
        body.add(to_where, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 155, 271, 49));

        date_panel.setBackground(new java.awt.Color(255, 255, 255));
        date_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(124, 141, 176), 1, true));
        date_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        date_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        date_label.setForeground(new java.awt.Color(124, 141, 176));
        date_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlineticketbookingsystem/assets/calender.png"))); // NOI18N
        date_label.setText("Departure date");
        date_panel.add(date_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, 176, 48));

        txt_date.setBackground(new java.awt.Color(255, 255, 255));
        txt_date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_date.setForeground(new java.awt.Color(124, 141, 176));
        txt_date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_dateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_dateFocusLost(evt);
            }
        });
        txt_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dateActionPerformed(evt);
            }
        });
        date_panel.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 210, 50));

        body.add(date_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(828, 154, 260, -1));

        search_btn.setBackground(new java.awt.Color(96, 93, 236));
        search_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search_btn.setForeground(new java.awt.Color(255, 255, 255));
        search_btn.setText("search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        body.add(search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1104, 154, -1, 49));

        table_panel.setBackground(new java.awt.Color(255, 255, 255));

        flight_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Flight name", "Source", "Destination", "Date", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        flight_tbl.setRowHeight(38);
        flight_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flight_tblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(flight_tbl);

        javax.swing.GroupLayout table_panelLayout = new javax.swing.GroupLayout(table_panel);
        table_panel.setLayout(table_panelLayout);
        table_panelLayout.setHorizontalGroup(
            table_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        table_panelLayout.setVerticalGroup(
            table_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        body.add(table_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 220, 920, 210));

        book_btn.setBackground(new java.awt.Color(96, 93, 236));
        book_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        book_btn.setForeground(new java.awt.Color(255, 255, 255));
        book_btn.setText("Book Flight");
        book_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_btnActionPerformed(evt);
            }
        });
        body.add(book_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, 100, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlineticketbookingsystem/assets/WorldMap.png"))); // NOI18N
        body.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 700));

        getContentPane().add(body, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillflight_tbl() {
        dtm.setRowCount(0);
        for (Flight flight : flights) {
            String fName = flight.getFlightName();
            String fSource = flight.getSource();
            String fDestination = flight.getDestination();
            String fDate = flight.getDate();
            String fTime = flight.getTime();
            dtm.addRow(new Object[]{fName, fSource, fDestination, fDate, fTime});
        }
        flight_tbl.setModel(dtm);
    }
    
    private void AccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new AccountUserPage().setVisible(true);
    }//GEN-LAST:event_AccountMouseClicked

    private void allflight_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allflight_btnActionPerformed
        // TODO add your handling code here:
        table_panel.setVisible(true);
        flights = flightDAO.getAllFlights();
        fillflight_tbl();
    }//GEN-LAST:event_allflight_btnActionPerformed

    private void to_whereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_to_whereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_to_whereActionPerformed

    private void txt_dateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_dateFocusGained
        // TODO add your handling code here:
        date_label.setText("");
    }//GEN-LAST:event_txt_dateFocusGained

    private void txt_dateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_dateFocusLost
        // TODO add your handling code here:
        if (txt_date.getText().isEmpty()) {
            date_label.setText("Departure date");
        }
    }//GEN-LAST:event_txt_dateFocusLost

    private void txt_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dateActionPerformed
        // TODO add your handling code here:
        date_label.setText("");
    }//GEN-LAST:event_txt_dateActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        table_panel.setVisible(true);
        String fromwhere = from_where.getSelectedItem().toString();
        String towhere = to_where.getSelectedItem().toString();
        String datet = txt_date.getText();
        if (!(fromwhere.equals("From Where ?") || towhere.equals("To Where ?") || datet.isEmpty())) {
            flights = flightDAO.searchFlights(fromwhere, towhere, datet);
            fillflight_tbl();
        }

    }//GEN-LAST:event_search_btnActionPerformed

    private void flight_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flight_tblMouseClicked
        // TODO add your handling code here:
        flight_tbl.getValueAt(flight_tbl.getSelectedRow(), flight_tbl.getSelectedColumn());
        AppSession.setcurrentFlight(flights.get(flight_tbl.getSelectedRow()));
        Flight fl = AppSession.getcurrentFlight();
        System.out.println(fl.getId());
        book_btn.setVisible(true);
    }//GEN-LAST:event_flight_tblMouseClicked

    private void book_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new BookPage().setVisible(true);  
    }//GEN-LAST:event_book_btnActionPerformed

    private void BookedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookedMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new BookedPage().setVisible(true);
    }//GEN-LAST:event_BookedMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("default".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Account;
    private javax.swing.JPanel BigSpace;
    private javax.swing.JLabel Booked;
    private javax.swing.JLabel Flights;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton allflight_btn;
    private javax.swing.JLabel background;
    private javax.swing.JPanel body;
    private javax.swing.JButton book_btn;
    private com.raven.datechooser.DateChooser date;
    private javax.swing.JLabel date_label;
    private javax.swing.JPanel date_panel;
    private javax.swing.JTable flight_tbl;
    private javax.swing.JComboBox<String> from_where;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton search_btn;
    private javax.swing.JLabel space1;
    private javax.swing.JLabel space2;
    private javax.swing.JLabel space3;
    private javax.swing.JPanel table_panel;
    private javax.swing.JComboBox<String> to_where;
    private javax.swing.JPanel toolbar;
    private javax.swing.JTextField txt_date;
    // End of variables declaration//GEN-END:variables
}
